---
permalink: sg6000/accessing-and-configuring-santricity-system-manager.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, SANtricity System Manager, SANtricity, System Manager, configure, configuring, setup, set up, setting up, access, accessing, E-Series AutoSupport, autosupport 
summary: Mit SANtricity System Manager lässt sich der Status von Storage Controllern, Storage-Festplatten und anderen Hardwarekomponenten im Storage Controller-Shelf überwachen. Sie können außerdem einen Proxy für AutoSupport der E-Series konfigurieren, mit dem Sie AutoSupport Meldungen von der Appliance senden können, ohne den Managementport zu verwenden. 
---
= Zugriff auf und Konfigurieren von SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SANtricity System Manager lässt sich der Status von Storage Controllern, Storage-Festplatten und anderen Hardwarekomponenten im Storage Controller-Shelf überwachen. Sie können außerdem einen Proxy für AutoSupport der E-Series konfigurieren, mit dem Sie AutoSupport Meldungen von der Appliance senden können, ohne den Managementport zu verwenden.

.Schritte
* link:setting-up-and-accessing-santricity-system-manager.html["Einrichten von SANtricity System Manager und Zugriff auf diese zugreifen"]
* link:reviewing-hardware-status-in-santricity-system-manager.html["Überprüfen des Hardwarestatus in SANtricity System Manager"]
* link:setting-ip-addresses-for-storage-controllers-using-storagegrid-appliance-installer.html["Festlegen der IP-Adressen für die Speichercontroller mithilfe des StorageGRID-Appliance-Installationsprogramms"]

