---
permalink: sg6000/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Bevor Sie eine StorageGRID-Appliance als Speicherknoten in einem StorageGRID-System bereitstellen können, müssen Sie die Verbindungen zwischen der Appliance und den zu verwendenden Netzwerken konfigurieren. Sie können Netzwerke konfigurieren, indem Sie das Installationsprogramm für die StorageGRID-Appliance suchen, das auf dem SG6000-CN-Controller \(dem Compute-Controller\) vorinstalliert ist.' 
---
= Konfigurieren von StorageGRID-Verbindungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine StorageGRID-Appliance als Speicherknoten in einem StorageGRID-System bereitstellen können, müssen Sie die Verbindungen zwischen der Appliance und den zu verwendenden Netzwerken konfigurieren. Sie können Netzwerke konfigurieren, indem Sie das Installationsprogramm der StorageGRID-Appliance durchsuchen, das auf dem SG6000-CN-Controller (dem Compute-Controller) vorinstalliert ist.

.Schritte
* link:accessing-storagegrid-appliance-installer-sg6000.html["Zugriff auf das Installationsprogramm der StorageGRID-Appliance"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Überprüfen und Aktualisieren der Installationsversion der StorageGRID Appliance"]
* link:configuring-network-links-sg6000.html["Konfigurieren von Netzwerkverbindungen (SG6000)"]
* link:configuring-storagegrid-ip-addresses-sg6000.html["StorageGRID-IP-Adressen werden konfiguriert"]
* link:verifying-network-connections.html["Netzwerkverbindungen werden überprüft"]
* link:verifying-port-level-network-connections.html["Überprüfen von Netzwerkverbindungen auf Portebene"]

