---
permalink: sg6000/configuring-bmc-interface-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, sg6000-cn, storage node, storage appliance, BMC, baseboard management controller, configure, setup, set up 
summary: 'Die Benutzeroberfläche für den Baseboard Management Controller \(BMC\) auf dem SG6000-CN Controller bietet Statusinformationen über die Hardware und ermöglicht die Konfiguration von SNMP-Einstellungen und anderen Optionen für den SG6000-CN Controller.' 
---
= Konfigurieren der BMC-Schnittstelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Benutzeroberfläche für den Baseboard Management Controller (BMC) auf dem SG6000-CN Controller bietet Statusinformationen über die Hardware und ermöglicht die Konfiguration von SNMP-Einstellungen und anderen Optionen für den SG6000-CN Controller.

.Schritte
* link:changing-root-password-for-bmc-interface-sg6000.html["Ändern des Root-Passworts für die BMC-Schnittstelle"]
* link:setting-ip-address-for-bmc-management-port-sg6000.html["Einstellen der IP-Adresse für den BMC-Managementport"]
* link:accessing-bmc-interface-sg6000.html["Zugriff auf die BMC-Schnittstelle"]
* link:configuring-snmp-settings-for-sg6000-cn-controller.html["Konfigurieren von SNMP-Einstellungen für den SG6000-CN-Controller"]
* link:setting-up-email-notifications-for-alerts.html["Einrichten von E-Mail-Benachrichtigungen für Meldungen"]

