---
permalink: sg6000/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: Das Installationsprogramm von StorageGRID Appliance ist möglicherweise nicht verfügbar, wenn Hardwarefehler oder Verkabelungsfehler die Speichercontroller oder den SG6000-CN-Controller daran hindern, ihre Boot-Verarbeitung abzuschließen. 
---
= Die Hardware-Einrichtung scheint zu hängen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Installationsprogramm von StorageGRID Appliance ist möglicherweise nicht verfügbar, wenn Hardwarefehler oder Verkabelungsfehler die Speichercontroller oder den SG6000-CN-Controller daran hindern, ihre Boot-Verarbeitung abzuschließen.

.Schritte
. Sehen Sie sich für die Speichercontroller die Codes in den sieben-Segment-Anzeigen an.
+
Während die Hardware beim Einschalten initialisiert wird, zeigen die beiden sieben Segmente eine Reihe von Codes an. Wenn die Hardware erfolgreich gebootet wurde, werden beide sieben Segmente angezeigt `99`.

. Überprüfen Sie die LEDs am SG6000-CN-Controller sowie die im BMC angezeigten Boot- und Fehlercodes.
. Wenn Sie Hilfe bei der Behebung eines Problems benötigen, wenden Sie sich an den technischen Support.


.Verwandte Informationen
link:viewing-boot-up-status-codes-for-sg6000-storage-controllers.html["Anzeigen von Boot-Statuscodes für die SG6000-Speicher-Controller"]

https://["E5700 und E2800 – System Monitoring Guide"^]

link:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.html["Anzeigen von Statusanzeigen und -Tasten auf dem SG6000-CN-Controller"]

link:viewing-boot-up-codes-for-sg6000-cn-controller.html["Anzeigen von Boot-Codes für den SG6000-CN-Controller"]

link:viewing-error-codes-for-sg6000-cn-controller.html["Anzeigen von Fehlercodes für den SG6000-CN-Controller"]
