---
permalink: sg6000/preparing-for-installation.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, install, installation, preparation, get ready, prepare 
summary: Die Vorbereitung der Installation einer StorageGRID Appliance umfasst die Vorbereitung des Standorts und den Erwerb aller erforderlichen Hardware, Kabel und Tools. Außerdem sollten Sie IP-Adressen und Netzwerkinformationen erfassen. 
---
= Installation wird vorbereitet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Vorbereitung der Installation einer StorageGRID Appliance umfasst die Vorbereitung des Standorts und den Erwerb aller erforderlichen Hardware, Kabel und Tools. Außerdem sollten Sie IP-Adressen und Netzwerkinformationen erfassen.

.Schritte
* link:preparing-site-sg6000.html["Vorbereiten der Site (SG6000)"]
* link:unpacking-boxes-sg6000.html["Auspacken der Boxen (SG6000)"]
* link:obtaining-additional-equipment-and-tools-sg6000.html["Beschaffung zusätzlicher Geräte und Werkzeuge (SG6000)"]
* link:web-browser-requirements.html["Anforderungen an einen Webbrowser"]
* link:reviewing-appliance-network-connections-sg6000.html["Überprüfen von Appliance-Netzwerkverbindungen"]
* link:gathering-installation-information-sg6000.html["Sammeln von Installationsinformationen (SG6000)"]

