---
permalink: audit/audit-message-overview.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, structure, content 
summary: Diese Anweisungen enthalten Informationen zur Struktur und zum Inhalt der StorageGRID-Prüfmeldungen und Prüfprotokolle. Sie können diese Informationen zum Lesen und Analysieren des Prüfprotokolls der Systemaktivität verwenden. 
---
= Übersicht über Überwachungsnachrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Anweisungen enthalten Informationen zur Struktur und zum Inhalt der StorageGRID-Prüfmeldungen und Prüfprotokolle. Sie können diese Informationen zum Lesen und Analysieren des Prüfprotokolls der Systemaktivität verwenden.

Diese Anweisungen richten sich an Administratoren, die für die Erstellung von Berichten zu Systemaktivitäten und -Nutzung verantwortlich sind, für die eine Analyse der Audit-Meldungen des StorageGRID Systems erforderlich ist.

Es wird davon ausgegangen, dass Sie die Art der geprüften Aktivitäten innerhalb des StorageGRID-Systems genau kennen. Um die Text-Log-Datei verwenden zu können, müssen Sie auf die konfigurierte Revisionsfreigabe im Admin-Knoten zugreifen können.

.Verwandte Informationen
link:../admin/index.html["StorageGRID verwalten"]
