---
permalink: audit/client-read-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client read, SGET, SHEA, WGET, WHEA, S3, swift 
summary: Client-Read-Audit-Meldungen werden protokolliert, wenn eine S3- oder Swift-Client-Applikation eine Anforderung zum Abrufen eines Objekts vorgibt. 
---
= Client liest Audit-Meldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Client-Read-Audit-Meldungen werden protokolliert, wenn eine S3- oder Swift-Client-Applikation eine Anforderung zum Abrufen eines Objekts vorgibt.

|===
| Codieren | Beschreibung | Verwendet von | Siehe 


 a| 
SGET
 a| 
S3 GET: Protokolliert eine erfolgreiche Transaktion, um ein Objekt abzurufen oder die Objekte in einem Bucket aufzulisten.

*Hinweis:* Wenn die Transaktion auf einer Unterressource ausgeführt wird, enthält die Audit-Nachricht das Feld S3SR.
 a| 
S3-Client
 a| 
link:sget-s3-get.html["SGET S3 ABRUFEN"]



 a| 
SHEA
 a| 
S3 HEAD: Protokolliert eine erfolgreiche Transaktion, um zu überprüfen, ob ein Objekt oder ein Bucket vorhanden ist.
 a| 
S3-Client
 a| 
link:shea-s3-head.html["SHEA: S3 KOPF"]



 a| 
WGET
 a| 
Swift GET: Protokolliert eine erfolgreiche Transaktion, um ein Objekt abzurufen oder die Objekte in einem Container aufzulisten.
 a| 
Swift Client
 a| 
link:wget-swift-get.html["WGET: Schneller ERHALTEN"]



 a| 
WHEA
 a| 
Swift HEAD: Protokolliert eine erfolgreiche Transaktion, um das Vorhandensein eines Objekts oder Containers zu überprüfen.
 a| 
Swift Client
 a| 
link:whea-swift-head.html["WHEA: Schneller KOPF"]

|===