---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 11.5 verwendet Version 3 der Mandantenmanagement-API. Version 3 depretiert Version 2; jedoch werden Version 1 und Version 2 weiterhin unterstützt. 
---
= Änderungen an der Mandantenmanagement-API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5 verwendet Version 3 der Mandantenmanagement-API. Version 3 depretiert Version 2; jedoch werden Version 1 und Version 2 weiterhin unterstützt.


IMPORTANT: Sie können weiterhin Version 1 und Version 2 der Management-API mit StorageGRID 11.5 verwenden. Die Unterstützung für diese Versionen der API wird jedoch in einem zukünftigen Release von StorageGRID entfernt. Nach dem Upgrade auf StorageGRID 11.5 können die veralteten v1- und v2-APIs mit dem deaktiviert werden `PUT /grid/config/management` API:



== Neuer Parameter für die Mandanten-Storage-Nutzung-API

Der `GET /org/usage` API hat jetzt eine `strictConsistency` Parameter. Um beim Abrufen von Speichernutzungsdaten über Speicherknoten eine stabile globale Konsistenz durchzusetzen, setzen Sie diesen Parameter auf `true`. Wenn dieser Parameter auf festgelegt ist `false` (Standard), StorageGRID versucht, Nutzungsdaten mit einer starken globalen Konsistenz abzurufen, kehrt aber zurück zu starker Standortkonsistenz, wenn starke globale Konsistenz nicht erreicht werden kann.

.Verwandte Informationen
link:../s3/index.html["S3 verwenden"]

link:../tenant/index.html["Verwenden Sie ein Mandantenkonto"]
