---
permalink: upgrade/downloading-recovery-package.html 
sidebar: sidebar 
keywords: recovery package, download 
summary: Die Wiederherstellungspakedatei ermöglicht Ihnen die Wiederherstellung des StorageGRID-Systems bei einem Fehler. 
---
= Herunterladen des Wiederherstellungspakets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Wiederherstellungspakedatei ermöglicht Ihnen die Wiederherstellung des StorageGRID-Systems bei einem Fehler.

.Was Sie benötigen
* Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.
* Sie müssen über eine Passphrase für die Bereitstellung verfügen.
* Sie müssen über spezifische Zugriffsberechtigungen verfügen.


.Über diese Aufgabe
Laden Sie die aktuelle Recovery Package-Datei herunter, bevor Sie Grid-Topologieänderungen am StorageGRID-System vornehmen oder bevor Sie Software aktualisieren. Laden Sie anschließend eine neue Kopie des Wiederherstellungspakets herunter, nachdem Sie Änderungen an der Grid-Topologie vorgenommen haben oder nachdem Sie die Software aktualisiert haben.

.Schritte
. Wählen Sie *Wartung* > *System* > *Wiederherstellungspaket*.
. Geben Sie die Provisionierungs-Passphrase ein, und wählen Sie *Download starten*.
+
Der Download startet sofort.

. Wenn der Download abgeschlossen ist:
+
.. Öffnen Sie das `.zip` Datei:
.. Bestätigen Sie, dass es ein enthält `gpt-backup` Telefonbuch und eine Innenausstattung `.zip` Datei:
.. Entnehmen Sie die Innenseite `.zip` Datei:
.. Bestätigen Sie, dass Sie den öffnen können `Passwords.txt` Datei:


. Kopieren Sie die heruntergeladene Wiederherstellungspaket-Datei (`.zip`) An zwei sichere und getrennte Stellen.
+

IMPORTANT: Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.



.Verwandte Informationen
link:../admin/index.html["StorageGRID verwalten"]
