---
permalink: sg100-1000/unable-to-connect-to-appliance-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: Wenn Sie keine Verbindung zur Services-Appliance herstellen können, liegt möglicherweise ein Netzwerkproblem vor, oder die Hardwareinstallation wurde möglicherweise nicht erfolgreich abgeschlossen. 
---
= Es konnte keine Verbindung zum Gerät hergestellt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie keine Verbindung zur Services-Appliance herstellen können, liegt möglicherweise ein Netzwerkproblem vor, oder die Hardwareinstallation wurde möglicherweise nicht erfolgreich abgeschlossen.

.Schritte
. Versuchen Sie, das Gerät mit der IP-Adresse des Geräts zu pingen : +
`*ping _services_appliance_IP_*`
. Wenn Sie keine Antwort vom Ping erhalten, bestätigen Sie, dass Sie die richtige IP-Adresse verwenden.
+
Sie können die IP-Adresse der Appliance im Grid-Netzwerk, im Admin-Netzwerk oder im Client-Netzwerk verwenden.

. Wenn die IP-Adresse korrekt ist, überprüfen Sie die Geräteverkabelung, QSFP- oder SFP-Transceiver und die Netzwerkeinrichtung.
+
Falls das Problem dadurch nicht behoben werden kann, wenden Sie sich an den technischen Support.

. Wenn der Ping erfolgreich war, öffnen Sie einen Webbrowser.
. Geben Sie die URL für das StorageGRID-Appliance-Installationsprogramm ein: +
`*https://_appliances_controller_IP_:8443*`
+
Die Startseite wird angezeigt.


