---
permalink: ubuntu/installation-overview.html 
sidebar: sidebar 
keywords:  
summary: Die Installation eines StorageGRID-Systems in einer Ubuntu- oder Debian-Umgebung umfasst drei primäre Schritte. 
---
= Übersicht über die Installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation eines StorageGRID-Systems in einer Ubuntu- oder Debian-Umgebung umfasst drei primäre Schritte.

. *Vorbereitung*: Bei der Planung und Vorbereitung führen Sie folgende Aufgaben aus:
+
** Erfahren Sie mehr über die Hardware- und Storage-Anforderungen für StorageGRID.
** Erfahren Sie mehr über die Besonderheiten des StorageGRID Networking, damit Sie Ihr Netzwerk entsprechend konfigurieren können. Weitere Informationen finden Sie in den StorageGRID Netzwerkrichtlinien.
** Ermitteln und Vorbereiten der physischen oder virtuellen Server, die Sie für das Hosten Ihrer StorageGRID Grid Nodes verwenden möchten
** Auf den Servern, die Sie vorbereitet haben:
+
*** Installieren Sie Ubuntu oder Debian
*** Konfigurieren Sie das Hostnetzwerk
*** Hostspeicher konfigurieren
*** Installation Von Docker
*** Installieren Sie die StorageGRID Host Services




. * Bereitstellung*: Bereitstellung von Grid-Knoten mit der entsprechenden Benutzeroberfläche. Wenn Sie Grid-Nodes implementieren, werden diese als Teil des StorageGRID Systems erstellt und mit einem oder mehreren Netzwerken verbunden.
+
.. Verwenden Sie die Ubuntu- oder Debian-Befehlszeile und Node-Konfigurationsdateien, um virtuelle Grid-Knoten auf den Hosts bereitzustellen, die Sie in Schritt 1 vorbereitet haben.
.. Verwenden Sie das Installationsprogramm für StorageGRID Appliance, um StorageGRID Appliance-Nodes bereitzustellen.
+

NOTE: Hardware-spezifische Installations- und Integrationsanweisungen sind nicht im Installationsverfahren für StorageGRID enthalten. Informationen zur Installation von StorageGRID Appliances finden Sie in der Installations- und Wartungsanleitung für Ihre Appliance.



. *Konfiguration*: Wenn alle Knoten bereitgestellt wurden, verwenden Sie den Grid Manager, um das Grid zu konfigurieren und die Installation abzuschließen.


Diese Anweisungen empfehlen einen Standardansatz für die Bereitstellung und Konfiguration eines StorageGRID-Systems in einer Ubuntu- oder Debian-Umgebung. Siehe auch die Informationen über folgende alternative Ansätze:

* Verwendung eines Standard-Orchestrierungs-Frameworks wie Ansible, Puppet oder Chef zur Installation von Ubuntu oder Debian, zur Konfiguration von Netzwerk und Storage, zur Installation von Docker und dem StorageGRID-Host-Service und zur Implementierung von virtuellen Grid-Nodes
* Automatisieren Sie die Implementierung und Konfiguration des StorageGRID Systems mit einem Python-Konfigurationsskript (im Installationsarchiv bereitgestellt).
* Automatisieren Sie die Implementierung und Konfiguration von Appliance-Grid-Nodes mit einem Python-Konfigurationsskript (erhältlich über das Installationsarchiv oder über das Installationsprogramm von StorageGRID Appliance).
* Als fortschrittlicher Entwickler von StorageGRID-Implementierungen sollten Sie die Installation VON REST-APIs verwenden, um die Installation von StorageGRID Grid-Nodes zu automatisieren.


.Verwandte Informationen
link:planning-and-preparation.html["Planung und Vorbereitung"]

link:deploying-virtual-grid-nodes.html["Implementierung virtueller Grid-Nodes"]

link:configuring-grid-and-completing-installation.html["Grid wird konfiguriert und die Installation abgeschlossen"]

link:automating-installation-and-configuration-of-storagegrid-host-service.html["Automatisierung der Installation und Konfiguration des StorageGRID Host Service"]

link:overview-of-installation-rest-api.html["Überblick über DIE REST API zur Installation"]

link:../network/index.html["Netzwerkrichtlinien"]
