---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords:  
summary: Sie müssen Ubuntu oder Debian auf allen Grid-Hosts installieren. Mit dem NetApp Interoperabilitäts-Matrix-Tool können Sie eine Liste der unterstützten Versionen abrufen. 
---
= Linux Wird Installiert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Ubuntu oder Debian auf allen Grid-Hosts installieren. Mit dem NetApp Interoperabilitäts-Matrix-Tool können Sie eine Liste der unterstützten Versionen abrufen.

.Schritte
. Installieren Sie Ubuntu oder Debian auf allen physischen oder virtuellen Grid-Hosts gemäß den Anweisungen des Distributors oder Ihrem Standardverfahren.
+

NOTE: Installieren Sie keine grafischen Desktop-Umgebungen. Bei der Installation von Ubuntu müssen Sie *Standard-Systemdienstprogramme* auswählen. Die Auswahl von *OpenSSH-Server* wird empfohlen, um SSH-Zugriff auf Ihre Ubuntu-Hosts zu aktivieren. Alle anderen Optionen können nicht ausgewählt werden.

. Stellen Sie sicher, dass alle Hosts Zugriff auf Ubuntu- oder Debian-Paket-Repositorys haben.
. Wenn Swap aktiviert ist:
+
.. Führen Sie den folgenden Befehl aus: `$ sudo swapoff --all`
.. Entfernen Sie alle Swap-Einträge aus `/etc/fstab` Um die Einstellungen zu erhalten.


+

IMPORTANT: Wenn Sie den Auslagerungsaustausch nicht vollständig deaktivieren, kann die Leistung erheblich gesenkt werden.



.Verwandte Informationen
https://["NetApp Interoperabilitäts-Matrix-Tool"^]
