---
permalink: network/client-network-requirements.html 
sidebar: sidebar 
keywords:  
summary: Das Client-Netzwerk ist optional. Wenn Sie ein Client-Netzwerk konfigurieren möchten, beachten Sie die folgenden Überlegungen. 
---
= Anforderungen an das Client-Netzwerk
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Client-Netzwerk ist optional. Wenn Sie ein Client-Netzwerk konfigurieren möchten, beachten Sie die folgenden Überlegungen.

Das Client Network unterstützt Datenverkehr von S3 und Swift Clients. Wenn konfiguriert, wird das Client-Netzwerk-Gateway zum Standard-Gateway des Node.

Wenn Sie ein Client-Netzwerk verwenden, können Sie StorageGRID vor feindlichen Angriffen schützen, indem Sie eingehenden Client-Datenverkehr nur auf explizit konfigurierten Load Balancer-Endpunkten akzeptieren. Weitere Informationen zum Verwalten des Lastausgleichs und zum Verwalten nicht vertrauenswürdiger Clientnetzwerke finden Sie in den Anweisungen zur Verwaltung von StorageGRID.

.Verwandte Informationen
link:../admin/index.html["StorageGRID verwalten"]
