---
permalink: network/host-network-configuration-for-docker-deployments.html 
sidebar: sidebar 
keywords:  
summary: 'Bevor Sie Ihre StorageGRID-Implementierung auf einer Docker-Container-Plattform starten, ermitteln Sie, welche Netzwerke \(Grid, Administrator, Client\) jeder Node verwenden soll. Sie müssen sicherstellen, dass die Netzwerkschnittstelle jedes Knotens auf der richtigen virtuellen oder physischen Host-Schnittstelle konfiguriert ist und dass jedes Netzwerk über ausreichende Bandbreite verfügt.' 
---
= Host-Netzwerkkonfiguration für Docker Implementierungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Ihre StorageGRID-Implementierung auf einer Docker-Container-Plattform starten, ermitteln Sie, welche Netzwerke (Grid, Administrator, Client) jeder Node verwenden soll. Sie müssen sicherstellen, dass die Netzwerkschnittstelle jedes Node auf der richtigen virtuellen oder physischen Host-Schnittstelle konfiguriert ist und dass jedes Netzwerk über ausreichende Bandbreite verfügt.



== Physische Hosts

Wenn Sie physische Hosts zur Unterstützung von Grid-Nodes verwenden:

* Stellen Sie sicher, dass alle Hosts für jede Node-Schnittstelle dieselbe Host-Schnittstelle verwenden. Diese Strategie vereinfacht die Host-Konfiguration und ermöglicht die zukünftige Node-Migration.
* Beziehen Sie eine IP-Adresse für den physischen Host selbst.
+

NOTE: Eine physische Schnittstelle auf dem Host kann vom Host selbst und von einem oder mehreren Nodes verwendet werden, die auf dem Host ausgeführt werden. Alle IP-Adressen, die dem Host oder Knoten über diese Schnittstelle zugewiesen sind, müssen eindeutig sein. Der Host und der Node können IP-Adressen nicht gemeinsam nutzen.

* Öffnen Sie die erforderlichen Ports zum Host.




== Empfehlungen für die minimale Bandbreite

In der folgenden Tabelle sind die Mindestempfehlungen für die jeweilige Art von StorageGRID Node und jeden Netzwerktyp aufgeführt. Sie müssen jeden physischen oder virtuellen Host mit ausreichender Netzwerkbandbreite bereitstellen, um die Mindestanforderungen an die Bandbreite für das Aggregat für die Gesamtzahl und den Typ der StorageGRID Nodes, die auf diesem Host ausgeführt werden sollen, zu erfüllen.

|===
| Node-Typ 3+| Netzwerktyp 


 a| 
| Raster | Admin | Client 


 a| 
Admin
| 10 Gbit/S | 1 Gbit/S | 1 Gbit/S 


 a| 
Gateway
| 10 Gbit/S | 1 Gbit/S | 10 Gbit/S 


 a| 
Storage
| 10 Gbit/S | 1 Gbit/S | 10 Gbit/S 


 a| 
Archivierung
| 10 Gbit/S | 1 Gbit/S | 10 Gbit/S 
|===

NOTE: Diese Tabelle enthält keine SAN-Bandbreite, die für den Zugriff auf Shared Storage erforderlich ist. Wenn Sie gemeinsam genutzten Storage verwenden, auf den Sie über Ethernet (iSCSI oder FCoE) zugreifen können, sollten Sie separate physische Schnittstellen für jeden Host bereitstellen, um ausreichend SAN-Bandbreite zur Verfügung zu stellen. Um einen Engpass zu vermeiden, sollte die SAN-Bandbreite für einen bestimmten Host in etwa der aggregierten Storage Node-Netzwerkbandbreite für alle Storage Nodes, die auf diesem Host ausgeführt werden, entsprechen.

Mithilfe der Tabelle können Sie die Mindestanzahl an Netzwerkschnittstellen bestimmen, die für jeden Host bereitgestellt werden sollen. Diese basieren auf der Anzahl und dem Typ der StorageGRID Nodes, die Sie auf diesem Host ausführen möchten.

So führen Sie beispielsweise einen Admin-Node, einen Gateway-Node und einen Storage-Node auf einem einzelnen Host aus:

* Verbinden Sie die Grid- und Admin-Netzwerke auf dem Admin-Node (erfordert 10 + 1 = 11 Gbit/s).
* Verbinden der Grid- und Client-Netzwerke auf dem Gateway-Node (erfordert 10 + 10 = 20 Gbit/s)
* Verbinden des Grid-Netzwerks mit dem Storage-Node (erfordert 10 Gbit/s)


In diesem Szenario sollten Sie mindestens 11 + 20 + 10 = 41 GBit/s Netzwerkbandbreite angeben, Dies konnte von zwei 40 Gbps Schnittstellen oder fünf 10 Gbps Schnittstellen erreicht werden, die möglicherweise in Trunks aggregiert und dann von den drei oder mehr VLANs, die die Grid-, Admin- und Client-Subnetze lokal zum physischen Rechenzentrum mit dem Host übertragen, gemeinsam genutzt werden.

Empfohlene Methoden zur Konfiguration physischer und Netzwerkressourcen auf den Hosts in Ihrem StorageGRID Cluster zur Vorbereitung der StorageGRID-Bereitstellung finden Sie in den Informationen zur Konfiguration des Hostnetzwerks in den Installationsanweisungen für Ihre Linux-Plattform.

.Verwandte Informationen
link:../rhel/index.html["Installieren Sie Red hat Enterprise Linux oder CentOS"]

link:../ubuntu/index.html["Installieren Sie Ubuntu oder Debian"]
