---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie Vorhaben, StorageGRID Plattform-Services oder Cloud-Storage-Pools zu verwenden, müssen Sie Grid-Netzwerke und Firewalls konfigurieren, um sicherzustellen, dass die Ziel-Endpunkte erreicht werden können. Zu den Plattform-Services gehören externe Services, die Integration von Suchvorgängen, Ereignisbenachrichtigungen und CloudMirror Replizierung ermöglichen. 
---
= Networking und Ports für Plattform-Services und Cloud Storage-Pools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Vorhaben, StorageGRID Plattform-Services oder Cloud-Storage-Pools zu verwenden, müssen Sie Grid-Netzwerke und Firewalls konfigurieren, um sicherzustellen, dass die Ziel-Endpunkte erreicht werden können. Zu den Plattform-Services gehören externe Services, die Integration von Suchvorgängen, Ereignisbenachrichtigungen und CloudMirror Replizierung ermöglichen.

Plattform-Services benötigen Zugriff von Storage-Nodes, die den StorageGRID ADC-Service für die externen Service-Endpunkte hosten. Beispiele für die Bereitstellung des Zugriffs:

* Konfigurieren Sie auf den Speicherknoten mit ADC-Diensten eindeutige Admin-Netzwerke mit AESL-Einträgen, die zu den Ziel-Endpunkten weiterleiten.
* Verlassen Sie sich auf die Standardroute, die von einem Client-Netzwerk bereitgestellt wird. In diesem Beispiel kann die Funktion UnTrusted Client Network verwendet werden, um eingehende Verbindungen einzuschränken.


Cloud-Storage-Pools erfordern außerdem Zugriff von Storage-Nodes auf die Endpunkte, die durch einen externen Service wie Amazon S3 Glacier oder Microsoft Azure Blob Storage bereitgestellt werden.

Standardmäßig verwenden Plattform-Services und Cloud-Storage-Pool-Kommunikation die folgenden Ports:

* *80*: Für Endpunkt-URIs, die mit beginnen `http`
* *443*: Für Endpunkt-URIs, die mit beginnen `https`


Ein anderer Port kann angegeben werden, wenn der Endpunkt erstellt oder bearbeitet wird.

Wenn Sie einen nicht transparenten Proxy-Server verwenden, müssen Sie auch Proxy-Einstellungen konfigurieren, damit Nachrichten an externe Endpunkte gesendet werden können, z. B. an einen Endpunkt im Internet. Weitere Informationen zum Konfigurieren der Proxy-Einstellungen finden Sie unter Verwalten von StorageGRID.

Weitere Informationen zu nicht vertrauenswürdigen Clientnetzwerken finden Sie in den Anweisungen zum Verwalten von StorageGRID. Weitere Informationen zu Plattform-Services finden Sie in der Anleitung zur Verwendung von Mandantenkonten. Weitere Informationen zu Cloud-Storage-Pools finden Sie in den Anweisungen zum Managen von Objekten mit Information Lifecycle Management.

.Verwandte Informationen
link:network-port-reference.html["Referenz für Netzwerk-Ports"]

link:../primer/index.html["Gittergrundierung"]

link:../admin/index.html["StorageGRID verwalten"]

link:../tenant/index.html["Verwenden Sie ein Mandantenkonto"]

link:../ilm/index.html["Objektmanagement mit ILM"]
