---
permalink: network/post-installation-guidelines.html 
sidebar: sidebar 
keywords:  
summary: Befolgen Sie nach Abschluss der Implementierung und Konfiguration des Grid-Node die folgenden Richtlinien für DHCP-Adressen und Änderungen der Netzwerkkonfiguration. 
---
= Richtlinien nach der Installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie nach Abschluss der Implementierung und Konfiguration des Grid-Node die folgenden Richtlinien für DHCP-Adressen und Änderungen der Netzwerkkonfiguration.

* Wenn DHCP zum Zuweisen von IP-Adressen verwendet wurde, konfigurieren Sie für jede IP-Adresse in den verwendeten Netzwerken eine DHCP-Reservierung.
+
Sie können DHCP nur während der Bereitstellungsphase einrichten. Sie können DHCP während der Konfiguration nicht einrichten.

+

IMPORTANT: Nodes werden neu gebootet, wenn sich ihre IP-Adressen ändern. Dies kann zu Ausfällen führen, wenn sich eine DHCP-Adresse gleichzeitig auf mehrere Nodes auswirkt.

* Sie müssen die Verfahren zum Ändern der IP-Adresse verwenden, wenn Sie IP-Adressen, Subnetzmaske und Standard-Gateways für einen Grid-Node ändern möchten. Informationen zum Konfigurieren von IP-Adressen finden Sie in den Wiederherstellungsanleitungen und Wartungsanweisungen.
* Wenn Sie Änderungen an der Netzwerkkonfiguration vornehmen, einschließlich Routing- und Gateway-Änderungen, geht die Client-Verbindung zum primären Admin-Node und anderen Grid-Nodes unter Umständen verloren. Abhängig von den vorgenommenen Netzwerkänderungen müssen Sie diese Verbindungen möglicherweise neu herstellen.


.Verwandte Informationen
link:../rhel/index.html["Installieren Sie Red hat Enterprise Linux oder CentOS"]

link:../ubuntu/index.html["Installieren Sie Ubuntu oder Debian"]

link:../vmware/index.html["VMware installieren"]

link:../sg100-1000/index.html["SG100  SG1000 Services-Appliances"]

link:../sg6000/index.html["SG6000 Storage-Appliances"]

link:../sg5700/index.html["SG5700 Storage-Appliances"]

link:../sg5600/index.html["SG5600 Storage Appliances"]

link:../maintain/index.html["Verwalten Sie  erholen"]
