---
permalink: sg5600/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Bevor Sie eine StorageGRID Appliance als Storage Node in einem StorageGRID-Grid bereitstellen können, müssen Sie die Verbindungen zwischen der Appliance und den zu verwendenden Netzwerken konfigurieren. Sie können das Netzwerk konfigurieren, indem Sie im StorageGRID Appliance Installer navigieren, der im E5600SG Controller \ (dem Compute-Controller in der Appliance\) enthalten ist.' 
---
= Konfigurieren von StorageGRID-Verbindungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine StorageGRID Appliance als Storage Node in einem StorageGRID-Grid bereitstellen können, müssen Sie die Verbindungen zwischen der Appliance und den zu verwendenden Netzwerken konfigurieren. Sie können das Netzwerk konfigurieren, indem Sie im StorageGRID Appliance Installer navigieren, der im E5600SG Controller (dem Computing-Controller in der Appliance) enthalten ist.

.Schritte
* link:accessing-storagegrid-appliance-installer-sg5600.html["Zugriff auf das Installationsprogramm der StorageGRID-Appliance"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Überprüfen und Aktualisieren der Installationsversion der StorageGRID Appliance"]
* link:configuring-network-links-sg5600.html["Konfigurieren von Netzwerkverbindungen (SG5600)"]
* link:setting-ip-configuration-sg5600.html["Einstellen der IP-Konfiguration"]
* link:verifying-network-connections.html["Netzwerkverbindungen werden überprüft"]
* link:verifying-port-level-network-connections.html["Überprüfen von Netzwerkverbindungen auf Portebene"]

