---
permalink: sg5600/installing-hardware.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, install, installing 
summary: Die Hardwareinstallation umfasst mehrere wichtige Aufgaben, einschließlich Installation von Hardwarekomponenten, Verkabelung dieser Komponenten und Konfiguration von Ports. 
---
= Installieren der Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Hardwareinstallation umfasst mehrere wichtige Aufgaben, einschließlich Installation von Hardwarekomponenten, Verkabelung dieser Komponenten und Konfiguration von Ports.

.Schritte
* link:registering-hardware.html["Registrieren der Hardware"]
* link:installing-appliance-in-cabinet-or-rack-sg5600.html["Installieren des Geräts in einem Schrank oder Rack (SG5600)"]
* link:cabling-appliance-sg5600.html["Verkabeln der Appliance (SG5600)"]
* link:connecting-ac-power-cords-sg5600.html["Anschließen der Netzstromkabel (SG5600)"]
* link:turning-power-on-sg5600.html["Einschalten (SG5600)"]
* link:viewing-boot-up-status-and-reviewing-error-codes-on-sg5600-controllers.html["Anzeigen des Boot-Status und Überprüfen von Fehlercodes auf den SG5600-Controllern"]

