---
permalink: sg5600/unable-to-connect-to-storagegrid-appliance-over-network.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: Wenn Sie keine Verbindung zur Appliance herstellen können, liegt möglicherweise ein Netzwerkproblem vor, oder die Hardwareinstallation wurde möglicherweise nicht erfolgreich abgeschlossen. 
---
= Es konnte keine Verbindung zur StorageGRID Appliance über das Netzwerk hergestellt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie keine Verbindung zur Appliance herstellen können, liegt möglicherweise ein Netzwerkproblem vor, oder die Hardwareinstallation wurde möglicherweise nicht erfolgreich abgeschlossen.

* *Ausgabe*
+
Sie können keine Verbindung zum Gerät herstellen.

* *Ursache*
+
Dies kann auftreten, wenn ein Netzwerkproblem auftritt oder die Hardwareinstallation nicht erfolgreich abgeschlossen wurde.

* *Korrekturmaßnahmen*
+
.. Pingen des Geräts: +
`*ping _E5600_controller_IP_*`
.. Öffnen Sie den StorageGRID Appliance Installer, indem Sie einen Browser öffnen und Folgendes eingeben: +
`*https://_Management_Port_IP_:8443*`
+
Geben Sie für Management_Port_IP die IP-Adresse für Management-Port 1 auf dem E5600SG-Controller ein (während der physischen Installation bereitgestellt).

.. Klicken Sie auf *Admin-Netzwerk konfigurieren*, und überprüfen Sie die IP.
.. Wenn Sie eine Antwort vom Ping erhalten, überprüfen Sie, ob Port 8443 in den Firewalls geöffnet ist.
.. Starten Sie die Appliance neu.
.. Aktualisieren Sie die Installationsseite.
.. Wenn das Verbindungsproblem dadurch nicht behoben werden kann, wenden Sie sich an den technischen Support über die NetApp Support Site unter http://["mysupport.netapp.com"^].




.Verwandte Informationen
link:e5600sg-controller-seven-segment-display-codes.html["E5600SG-Controller-Anzeigecodes für sieben Segmente"]
