---
permalink: tenant/using-search-integration-service.html 
sidebar: sidebar 
keywords: storagegrid, tenant, search integration, search integration service, configuring search integration, configure search integration 
summary: Der Suchintegrations-Service ist einer der drei StorageGRID Plattform-Services. Sie können diesen Service aktivieren, wenn ein Objekt erstellt, gelöscht oder seine Metadaten oder Tags aktualisiert wird, Objektmetadaten an einen Zielsuchindex zu senden. 
---
= Verwenden des Suchintegrationsdienstes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Suchintegrations-Service ist einer der drei StorageGRID Plattform-Services. Sie können diesen Service aktivieren, wenn ein Objekt erstellt, gelöscht oder seine Metadaten oder Tags aktualisiert wird, Objektmetadaten an einen Zielsuchindex zu senden.

Sie können die Suchintegration mit dem Mandanten-Manager konfigurieren, um eine benutzerdefinierte StorageGRID-Konfigurations-XML auf einen Bucket anzuwenden.


NOTE: Da der Suchintegrationsdienst dazu führt, dass Objektmetadaten an ein Ziel gesendet werden, wird seine Konfigurations-XML als _Metadaten Notification Configuration XML_ bezeichnet. Diese Konfigurations-XML unterscheidet sich von der XML-Konfiguration _notification_, die zur Aktivierung von Ereignisbenachrichtigungen verwendet wird.

Anweisungen zur Implementierung von S3-Client-Applikationen finden Sie in der Anleitung zu den folgenden benutzerdefinierten StorageGRID S3-REST-API-Vorgängen:

* Konfigurationsanforderung für Bucket-Metadaten-Benachrichtigungen LÖSCHEN
* Konfigurationsanforderung FÜR Bucket-Metadaten-Benachrichtigungen ABRUFEN
* PUT Anforderung der Bucket-Metadaten-Benachrichtigung


.Verwandte Informationen
link:configuration-xml-for-search-configuration.html["Konfigurations-XML für die Integration der Suche"]

link:object-metadata-included-in-metadata-notifications.html["Objektmetadaten sind in Metadaten-Benachrichtigungen enthalten"]

link:json-generated-by-search-integration-service.html["Vom Suchintegrations-Service generierter JSON"]

link:configuring-search-integration-service.html["Konfigurieren des Suchintegrationsservice"]

link:../s3/index.html["S3 verwenden"]
