---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords:  
summary: Die Implementierung von StorageGRID Grid-Nodes in VMware vSphere lässt sich automatisieren. 
---
= Automatisierung der Grid Node-Implementierung in VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Implementierung von StorageGRID Grid-Nodes in VMware vSphere lässt sich automatisieren.

.Was Sie benötigen
* Sie haben Zugriff auf ein Linux/Unix System mit Bash 3.2 oder höher.
* Sie haben VMware OVF Tool 4.1 installiert und richtig konfiguriert.
* Sie kennen den Benutzernamen und das Kennwort, die für den Zugriff auf VMware vSphere mit dem OVF-Tool erforderlich sind.
* Sie kennen die VI-URL der virtuellen Infrastruktur für den Speicherort in vSphere, wo Sie die StorageGRID Virtual Machines bereitstellen möchten. Bei dieser URL handelt es sich in der Regel um eine vApp oder einen Ressourcen-Pool. Beispiel: `vi://vcenter.example.com/vi/sgws`
+

NOTE: Sie können VMware verwenden `ovftool` Dienstprogramm, um diesen Wert zu ermitteln (siehe `ovftool` Dokumentation für Details).

+

NOTE: Wenn Sie eine vApp bereitstellen, werden die virtuellen Maschinen nicht automatisch beim ersten Mal gestartet, und Sie müssen sie manuell einschalten.

* Sie haben alle für die Konfigurationsdatei erforderlichen Informationen gesammelt. Siehe link:collecting-information-about-your-deployment-environment.html["Sammeln von Informationen über die Bereitstellungsumgebung"] Zur Information.
* Sie haben Zugriff auf die folgenden Dateien aus dem VMware Installationsarchiv für StorageGRID:


[cols="1a,1a"]
|===
| Dateiname | Beschreibung 


| NetApp-SG-Version-SHA.vmdk  a| 
Die Festplattendatei für Virtual Machines, die als Vorlage für die Erstellung von Grid-Node-Virtual Machines verwendet wird.

*Hinweis:* Diese Datei muss sich im selben Ordner befinden wie der `.ovf` Und `.mf` Dateien:



| vsphere-Primary-admin.ovf vsphere-Primary-admin.mf  a| 
Die Vorlagendatei „Open Virtualization Format“ (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung des primären Admin-Knotens.



| vsphere-nicht-Primary-admin.ovf vsphere-nicht-Primary-admin.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von nicht-primären Admin-Knoten.



| vsphere-Archive.ovf vsphere-Archive.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von Archiv-Knoten.



| vsphere-Gateway.ovf vsphere-Gateway.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von Gateway-Knoten.



| vsphere-Storage.ovf vsphere-Storage.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Zur Bereitstellung von virtuellen Maschinen-basierten Speicherknoten.



| deploy-vsphere-ovftool.sh  a| 
Das Bash Shell-Skript wird zur Automatisierung der Implementierung virtueller Grid-Nodes verwendet.



| deploy-vsphere-ovftool-sample.ini  a| 
Die Beispielkonfigurationsdatei für die Verwendung mit dem `deploy-vsphere-ovftool.sh` Skript:

|===