---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, vmware, download installation files, downloading installation files 
summary: Sie müssen die StorageGRID-Installationsarchive herunterladen und die Dateien extrahieren. 
---
= Herunterladen und Extrahieren der StorageGRID-Installationsdateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die StorageGRID-Installationsarchive herunterladen und die Dateien extrahieren.

.Schritte
. StorageGRID finden Sie auf der Seite zu NetApp Downloads.
+
https://["NetApp Downloads: StorageGRID"^]

. Wählen Sie die Schaltfläche zum Herunterladen der neuesten Version, oder wählen Sie eine andere Version aus dem Dropdown-Menü aus und wählen Sie *Go*.
. Melden Sie sich mit Ihrem Benutzernamen und Passwort für Ihr NetApp Konto an.
. Wenn eine Warnung/MusterLeseanweisung angezeigt wird, lesen Sie sie, und aktivieren Sie das Kontrollkästchen.
+
Nachdem Sie die StorageGRID Version installiert haben, müssen Sie alle erforderlichen Hotfixes anwenden. Weitere Informationen finden Sie im Hotfix-Verfahren in den Recovery- und Wartungsanleitungen.

. Lesen Sie die Endbenutzer-Lizenzvereinbarung, aktivieren Sie das Kontrollkästchen und wählen Sie dann *Akzeptieren und fortfahren*.
. Wählen Sie in der Spalte *Install StorageGRID* die entsprechende Software aus.
+
Laden Sie die herunter `.tgz` Oder `.zip` Archivieren Sie die Datei für Ihre Plattform.

+
** `StorageGRID-Webscale-version-VMware-uniqueID.zip`
** `StorageGRID-Webscale-version-VMware-uniqueID.tgz`





NOTE: Verwenden Sie die `.zip` Datei, wenn Windows auf dem Service-Laptop ausgeführt wird.

. Speichern und extrahieren Sie die Archivdatei.
. Wählen Sie aus der folgenden Liste die benötigten Dateien aus.
+
Die benötigten Dateien hängen von der geplanten Grid-Topologie und der Implementierung des StorageGRID Systems ab.




NOTE: Die in der Tabelle aufgeführten Pfade beziehen sich auf das Verzeichnis der obersten Ebene, das vom extrahierten Installationsarchiv installiert wird.

[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./vsphere/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./vsphere/NLF000000.txt  a| 
Eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



| ./vsphere/NetApp-SG-Version-SHA.vmdk  a| 
Die Festplattendatei für Virtual Machines, die als Vorlage für die Erstellung von Grid-Node-Virtual Machines verwendet wird.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Die Vorlagendatei „Open Virtualization Format“ (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung des primären Admin-Knotens.



| ./vsphere/vsphere-nicht-primäre-admin.ovf ./vsphere/vsphere-nicht-primäre-admin.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von nicht-primären Admin-Knoten.



| ./vsphere/vsphere-Archive.ovf ./vsphere/vsphere-Archive.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von Archiv-Knoten.



| ./vsphere/vsphere-Gateway.ovf ./vsphere/vsphere-Gateway.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von Gateway-Knoten.



| ./vsphere/vsphere-Storage.ovf ./vsphere/vsphere-Storage.mf  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Zur Bereitstellung von virtuellen Maschinen-basierten Speicherknoten.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Ein Bash Shell-Skript, das zur Automatisierung der Implementierung virtueller Grid-Nodes verwendet wird.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `deploy-vsphere-ovftool.sh` Skript:



| ./vsphere/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./vsphere/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./vsphere/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können.



| ./vsphere/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./vsphere/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:

|===
.Verwandte Informationen
link:../maintain/index.html["Verwalten Sie  erholen"]
