---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: storagegrid, rhel, redhat, redhat linux, automating installation, automate installation 
summary: Die Installation des StorageGRID Host Service und die Konfiguration der Grid-Nodes lassen sich automatisieren. 
---
= Automatisierung der Installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation des StorageGRID Host Service und die Konfiguration der Grid-Nodes lassen sich automatisieren.

.Über diese Aufgabe
Eine Automatisierung der Implementierung kann in einem der folgenden Fälle von Nutzen sein:

* Sie verwenden bereits ein Standard-Orchestrierungs-Framework wie Ansible, Puppet oder Chef für die Implementierung und Konfiguration physischer oder virtueller Hosts.
* Sie beabsichtigen, mehrere StorageGRID Instanzen zu implementieren.
* Sie implementieren eine große, komplexe StorageGRID Instanz.


Der StorageGRID Host Service wird durch ein Paket installiert und unterstützt durch Konfigurationsdateien, die während einer manuellen Installation interaktiv erstellt oder vorab (oder programmgesteuert) vorbereitet werden können, um eine automatisierte Installation mithilfe von Standard-Orchestrierungs-Frameworks zu ermöglichen. StorageGRID bietet optionale Python-Skripte zur Automatisierung der Konfiguration von StorageGRID Appliances und dem gesamten StorageGRID-System (das „`Grid`“). Sie können diese Skripte direkt verwenden oder sie informieren, wie Sie die StorageGRID Installations-REST-API bei den von Ihnen selbst entwickelten Grid-Implementierungs- und Konfigurations-Tools verwenden.

Wenn Sie daran interessiert sind, Ihre StorageGRID-Implementierung vollständig oder teilweise zu automatisieren, lesen Sie vor Beginn des Installationsprozesses „`Automatisieren der Installation`“ durch.
