---
permalink: rhel/installation-overview.html 
sidebar: sidebar 
keywords: storagegrid, rhel installation, redhat installation, redhat linux, centos installation 
summary: 'Die Installation eines StorageGRID Systems in einer Red hat Enterprise Linux \(RHEL\) oder CentOS Linux Umgebung umfasst drei wichtige Schritte.' 
---
= Übersicht über die Installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation eines StorageGRID Systems in einer Red hat Enterprise Linux (RHEL) oder CentOS Linux Umgebung umfasst drei wichtige Schritte.

. *Vorbereitung*: Bei der Planung und Vorbereitung führen Sie folgende Aufgaben aus:
+
** Erfahren Sie mehr über die Hardware- und Storage-Anforderungen für StorageGRID.
** Erfahren Sie mehr über die Besonderheiten des StorageGRID Networking, damit Sie Ihr Netzwerk entsprechend konfigurieren können. Weitere Informationen finden Sie in den StorageGRID Netzwerkrichtlinien.
** Ermitteln und Vorbereiten der physischen oder virtuellen Server, die Sie für das Hosten Ihrer StorageGRID Grid Nodes verwenden möchten
** Auf den Servern, die Sie vorbereitet haben:
+
*** Installieren Sie Linux
*** Konfigurieren Sie das Hostnetzwerk
*** Hostspeicher konfigurieren
*** Installation Von Docker
*** Installieren Sie die StorageGRID Host Services




. * Bereitstellung*: Bereitstellung von Grid-Knoten mit der entsprechenden Benutzeroberfläche. Wenn Sie Grid-Nodes implementieren, werden diese als Teil des StorageGRID Systems erstellt und mit einem oder mehreren Netzwerken verbunden.
+
.. Verwenden Sie die Linux-Befehlszeile und die Node-Konfigurationsdateien, um auf den in Schritt 1 vorbereiteten Hosts softwarebasierte Grid-Nodes bereitzustellen.
.. Verwenden Sie das Installationsprogramm für StorageGRID Appliance, um StorageGRID Appliance-Nodes bereitzustellen.
+

NOTE: Hardware-spezifische Installations- und Integrationsanweisungen sind nicht im Installationsverfahren für StorageGRID enthalten. Informationen zur Installation von StorageGRID Appliances finden Sie in der Installations- und Wartungsanleitung für Ihre Appliance.



. *Konfiguration*: Wenn alle Knoten bereitgestellt wurden, verwenden Sie den StorageGRIDGrid Manager, um das Grid zu konfigurieren und die Installation abzuschließen.


Diese Anweisungen empfehlen einen Standardansatz zur Implementierung und Konfiguration eines StorageGRID Systems. Siehe auch die Informationen über folgende alternative Ansätze:

* Verwendung eines Standard-Orchestrierungs-Frameworks wie Ansible, Puppet oder Chef zur Installation von RHEL oder CentOS, zur Konfiguration von Netzwerk und Storage, zur Installation von Docker und dem StorageGRID Host Service sowie zur Implementierung von virtuellen Grid-Nodes
* Automatisieren Sie die Implementierung und Konfiguration des StorageGRID Systems mit einem Python-Konfigurationsskript (im Installationsarchiv bereitgestellt).
* Automatisieren Sie die Implementierung und Konfiguration von Appliance-Grid-Nodes mit einem Python-Konfigurationsskript (erhältlich über das Installationsarchiv oder über das Installationsprogramm von StorageGRID Appliance).
* Als fortschrittlicher Entwickler von StorageGRID-Implementierungen sollten Sie die Installation VON REST-APIs verwenden, um die Installation von StorageGRID Grid-Nodes zu automatisieren.


.Verwandte Informationen
link:planning-and-preparation.html["Planung und Vorbereitung"]

link:deploying-virtual-grid-nodes.html["Implementierung virtueller Grid-Nodes"]

link:configuring-grid-and-completing-installation.html["Grid wird konfiguriert und die Installation abgeschlossen"]

link:automating-installation.html["Automatisierung der Installation"]

link:overview-of-installation-rest-api.html["Überblick über DIE REST API zur Installation"]

link:../network/index.html["Netzwerkrichtlinien"]
