---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie ein lokaler Benutzer des Grid Managers sind, können Sie Ihr eigenes Passwort ändern. 
---
= Ihr Passwort wird geändert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein lokaler Benutzer des Grid Managers sind, können Sie Ihr eigenes Passwort ändern.

.Was Sie benötigen
Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.

.Über diese Aufgabe
Wenn Sie sich bei StorageGRID als föderierten Benutzer anmelden oder SSO (Single Sign On) aktiviert ist, können Sie Ihr Kennwort im Grid Manager nicht ändern. Stattdessen müssen Sie Ihr Passwort in der externen Identitätsquelle ändern, z. B. Active Directory oder OpenLDAP.

.Schritte
. Wählen Sie in der Kopfzeile des Grid Managers *_your Name_ > Passwort ändern*.
. Geben Sie Ihr aktuelles Kennwort ein.
. Geben Sie ein neues Passwort ein.
+
Ihr Kennwort muss mindestens 8 und höchstens 32 Zeichen enthalten. Bei Passwörtern wird die Groß-/Kleinschreibung berücksichtigt.

. Geben Sie das neue Passwort erneut ein.
. Klicken Sie Auf *Speichern*.

