---
permalink: admin/completing-archive-node-setup.html 
sidebar: sidebar 
keywords:  
summary: Der Archivknoten funktioniert nicht, nachdem Sie den Installationsprozess abgeschlossen haben. Bevor das StorageGRID-System Objekte auf dem TSM-Archivknoten speichern kann, müssen Sie die Installation und Konfiguration des TSM-Servers abschließen und den Archivknoten für die Kommunikation mit dem TSM-Server konfigurieren. 
---
= Abschluss der Konfiguration des Archivierungs-Knotens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Archivknoten funktioniert nicht, nachdem Sie den Installationsprozess abgeschlossen haben. Bevor das StorageGRID-System Objekte auf dem TSM-Archivknoten speichern kann, müssen Sie die Installation und Konfiguration des TSM-Servers abschließen und den Archivknoten für die Kommunikation mit dem TSM-Server konfigurieren.

Weitere Informationen zur Optimierung von TSM-Abruf- und Speichersitzungen finden Sie unter Informationen zum Management von Archivspeicher.

* link:managing-archive-nodes.html["Verwalten Von Archivierungs-Knoten"]


Beachten Sie bei Bedarf die folgende IBM-Dokumentation, wenn Sie Ihren TSM-Server für die Integration mit dem Archiv-Node in einem StorageGRID-System vorbereiten:

* http://["IBM Bandgerätetreiber – Installations- und Benutzerhandbuch"^]
* http://["Programmierreferenz für IBM Bandgerätetreiber"^]

