---
permalink: admin/configuring-tsm-server.html 
sidebar: sidebar 
keywords:  
summary: Dieser Abschnitt enthält Beispielanweisungen zur Vorbereitung eines TSM-Servers gemäß den Best Practices von TSM. 
---
= Konfigurieren des TSM-Servers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt enthält Beispielanweisungen zur Vorbereitung eines TSM-Servers gemäß den Best Practices von TSM.

Die folgenden Anweisungen führen Sie durch den Prozess von:

* Definieren eines Festplatten-Speicherpools und eines Bandspeicherpools (falls erforderlich) auf dem TSM-Server
* Definieren einer Domänenrichtlinie, die die TSM-Managementklasse für die Daten verwendet, die im Knoten Archiv gespeichert sind, und Registrieren eines Knotens für diese Domänenrichtlinie


Diese Anweisungen dienen nur zu Ihrer Orientierung. Sie dienen nicht als Ersatz für die TSM Dokumentation oder zur Bereitstellung der vollständigen und umfassenden Anweisungen für alle Konfigurationen. Eine Anleitung zur Implementierung sollte von einem TSM-Administrator bereitgestellt werden, der sowohl mit Ihren detaillierten Anforderungen als auch mit dem vollständigen Satz der TSM-Server-Dokumentation vertraut ist.
