---
permalink: admin/confirming-capacity-of-storagegrid-system.html 
sidebar: sidebar 
keywords:  
summary: Bevor Sie große Datenmengen in das StorageGRID System migrieren, vergewissern Sie sich, dass das StorageGRID System über die Festplattenkapazität verfügt, um das erwartete Volume zu verwalten. 
---
= Bestätigen der Kapazität des StorageGRID Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie große Datenmengen in das StorageGRID System migrieren, vergewissern Sie sich, dass das StorageGRID System über die Festplattenkapazität verfügt, um das erwartete Volume zu verwalten.

Wenn das StorageGRID-System einen Archivknoten umfasst und eine Kopie migriertes Objekt in Nearline-Speicher (z. B. Band) gespeichert wurde, stellen Sie sicher, dass der Speicher des Archivknotens über ausreichende Kapazität für das erwartete Volumen migriertes Datenvolumen verfügt.

Sehen Sie sich als Teil der Kapazitätsbewertung das Datenprofil der zu migrierenden Objekte an und berechnen Sie die erforderliche Festplattenkapazität. Weitere Informationen zum Monitoring der Festplattenkapazität Ihres StorageGRID Systems finden Sie in den Anweisungen für das Monitoring und die Fehlerbehebung von StorageGRID.

.Verwandte Informationen
link:../monitor/index.html["Monitor  Fehlerbehebung"]

link:managing-storage-nodes.html["Verwalten Von Storage-Nodes"]
