---
permalink: admin/configuring-sso.html 
sidebar: sidebar 
keywords:  
summary: 'Wenn Single Sign-On \(SSO\) aktiviert ist, können Benutzer nur auf den Grid Manager, den Mandantenmanager, die Grid Management API oder die Mandantenmanagement-API zugreifen, wenn ihre Anmeldedaten über den von Ihrer Organisation implementierten SSO-Anmeldeprozess autorisiert sind.' 
---
= Konfigurieren der Single Sign-On-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Single Sign-On (SSO) aktiviert ist, können Benutzer nur auf den Grid Manager, den Mandanten-Manager, die Grid-Management-API oder die Mandantenmanagement-API zugreifen, wenn ihre Anmeldedaten über den von Ihrem Unternehmen implementierten SSO-Anmeldeprozess autorisiert sind.

* link:confirming-federated-users-can-sign-in.html["Bestätigung der föderierten Benutzer kann sich anmelden"]
* link:using-sandbox-mode.html["Sandbox-Modus verwenden"]
* link:creating-relying-party-trusts-in-ad-fs.html["Erstellen von Vertrauensstellungen von Vertrauensstellen in AD FS"]
* link:testing-relying-party-trusts.html["Testen von Vertrauen von Vertrauensstellen"]
* link:enabling-single-sign-on.html["Aktivieren von Single Sign On"]
* link:disabling-single-sign-on.html["Deaktivieren der Einzelanmeldung"]
* link:temporarily-disabling-and-reenabling-sso-for-admin-node.html["Vorübergehend deaktivieren und erneut aktivieren der Single Sign-On für einen Admin-Knoten"]

