---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID unterstützt bis zu drei Netzwerkschnittstellen pro Grid Node. So können Sie das Netzwerk für jeden einzelnen Grid Node so konfigurieren, dass die Sicherheits- und Zugriffsanforderungen erfüllt werden. 
---
= Richtlinien für StorageGRID-Netzwerke
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID unterstützt bis zu drei Netzwerkschnittstellen pro Grid Node. So können Sie das Netzwerk für jeden einzelnen Grid Node so konfigurieren, dass die Sicherheits- und Zugriffsanforderungen erfüllt werden.


NOTE: Informationen zum Ändern oder Hinzufügen eines Netzwerks für einen Grid-Node finden Sie in den Recovery- und Wartungsanweisungen. Weitere Informationen zur Netzwerktopologie finden Sie in den Netzwerkanweisungen.



== Grid-Netzwerk

Erforderlich. Das Grid-Netzwerk wird für den gesamten internen StorageGRID-Datenverkehr verwendet. Das System bietet Konnektivität zwischen allen Nodes im Grid und allen Standorten und Subnetzen.



== Admin-Netzwerk

Optional Das Admin-Netzwerk wird in der Regel für die Systemadministration und -Wartung verwendet. Sie kann auch für den Zugriff auf das Client-Protokoll verwendet werden. Das Admin-Netzwerk ist in der Regel ein privates Netzwerk und muss nicht zwischen Standorten routingfähig sein.



== Client-Netzwerk

Optional Das Client-Netzwerk ist ein offenes Netzwerk, das normalerweise für den Zugriff auf S3- und Swift-Client-Applikationen verwendet wird, sodass das Grid-Netzwerk isoliert und gesichert werden kann. Das Client-Netzwerk kann mit jedem Subnetz kommunizieren, das über das lokale Gateway erreichbar ist.



== Richtlinien

* Jeder StorageGRID Grid Node benötigt für jedes ihm zugewiesene Netzwerk eine dedizierte Netzwerkschnittstelle, eine IP-Adresse, eine Subnetzmaske und ein Gateway.
* Ein Grid-Node kann nicht mehr als eine Schnittstelle in einem Netzwerk haben.
* Es wird ein einzelnes Gateway pro Netzwerk und pro Grid-Node unterstützt, das sich im gleichen Subnetz wie der Node befindet. Sie können bei Bedarf komplexere Routing-Lösungen im Gateway implementieren.
* Auf jedem Node ist jedes Netzwerk einer bestimmten Netzwerkschnittstelle zugeordnet.
+
[cols="1a,1a"]
|===
| Netzwerk | Schnittstellenname 


 a| 
Raster
 a| 
Eth0



 a| 
Admin (optional)
 a| 
Eth1



 a| 
Client (optional)
 a| 
Eth2

|===
* Wenn der Node mit einer StorageGRID Appliance verbunden ist, werden für jedes Netzwerk bestimmte Ports verwendet. Weitere Informationen finden Sie in den Installationsanweisungen für Ihr Gerät.
* Die Standardroute wird automatisch pro Knoten generiert. Wenn eth2 aktiviert ist, verwendet 0.0.0.0/0 das Client-Netzwerk auf eth2. Wenn eth2 nicht aktiviert ist, verwendet 0.0.0.0/0 das Grid-Netzwerk auf eth0.
* Das Client-Netzwerk ist erst betriebsbereit, wenn der Grid-Node dem Grid beigetreten ist
* Das Admin-Netzwerk kann während der Bereitstellung des Grid-Knotens konfiguriert werden, um den Zugriff auf die Installations-Benutzeroberfläche zu ermöglichen, bevor das Grid vollständig installiert ist.


.Verwandte Informationen
link:../maintain/index.html["Verwalten Sie  erholen"]

link:../network/index.html["Netzwerkrichtlinien"]
