---
permalink: admin/kms-adding.html 
sidebar: sidebar 
keywords:  
summary: Mithilfe des Assistenten für den StorageGRID-Verschlüsselungsmanagement-Server können Sie jeden KMS- oder KMS-Cluster hinzufügen. 
---
= Hinzufügen eines Verschlüsselungsmanagement-Servers (KMS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe des Assistenten für den StorageGRID-Verschlüsselungsmanagement-Server können Sie jeden KMS- oder KMS-Cluster hinzufügen.

.Was Sie benötigen
* Sie müssen den geprüft haben link:kms-considerations-and-requirements.html["Überlegungen und Anforderungen für die Verwendung eines Verschlüsselungsmanagement-Servers"].
* Dieser muss unbedingt vorhanden sein link:kms-configuring-storagegrid-as-client.html["StorageGRID wurde als Client im KMS konfiguriert"], Und Sie müssen die erforderlichen Informationen für jeden KMS- oder KMS-Cluster haben
* Sie müssen über die Berechtigung Root Access verfügen.
* Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.


.Über diese Aufgabe
Konfigurieren Sie, falls möglich, Site-spezifische Verschlüsselungsmanagement-Server, bevor Sie einen Standard-KMS konfigurieren, der für alle Standorte gilt, die nicht von einem anderen KMS gemanagt werden. Wenn Sie zuerst den Standard-KMS erstellen, werden alle Node-verschlüsselten Appliances im Grid durch den Standard-KMS verschlüsselt. Wenn Sie später einen Site-spezifischen KMS erstellen möchten, müssen Sie zuerst die aktuelle Version des Verschlüsselungsschlüssels vom Standard-KMS auf den neuen KMS kopieren.

link:kms-considerations-for-changing-for-site.html["Überlegungen für das Ändern des KMS für einen Standort"]

.Schritte
. link:kms-adding-enter-kms-details.html["Schritt 1: Geben Sie KMS-Details ein"]
. link:kms-adding-upload-server-certificate.html["Schritt: Serverzertifikat Hochladen"]
. link:kms-adding-upload-client-certificates.html["Schritt 3: Laden Sie Client-Zertifikate Hoch"]

