---
permalink: admin/requirements-for-sso.html 
sidebar: sidebar 
keywords:  
summary: 'Bevor Sie Single Sign-On \(SSO\) für ein StorageGRID-System aktivieren, überprüfen Sie die Anforderungen in diesem Abschnitt.' 
---
= Anforderungen für die Nutzung von Single Sign On
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Single Sign On (SSO) für ein StorageGRID-System aktivieren, überprüfen Sie die Anforderungen in diesem Abschnitt.


IMPORTANT: Single Sign-On (SSO) ist auf den Ports Restricted Grid Manager oder Tenant Manager nicht verfügbar. Sie müssen den Standard-HTTPS-Port (443) verwenden, wenn Benutzer sich mit Single Sign-On authentifizieren möchten.



== Anforderungen an Identitätsanbieter

Der Identitäts-Provider (IdP) für SSO muss die folgenden Anforderungen erfüllen:

* Eine der folgenden Versionen des Active Directory Federation Service (AD FS):
+
** AD FS 4.0, im Lieferumfang von Windows Server 2016 enthalten
+

NOTE: Windows Server 2016 sollte den verwenden https://support.microsoft.com/en-us/help/3201845/cumulative-update-for-windows-10-version-1607-and-windows-server-2016["KB3201845-Update"^], Oder höher.

** AD FS 3.0, im Lieferumfang von Windows Server 2012 R2 Update oder höher enthalten.


* Transport Layer Security (TLS) 1.2 oder 1.3
* Microsoft .NET Framework, Version 3.5.1 oder höher




== Serverzertifikate-Anforderungen

StorageGRID verwendet auf jedem Admin-Node ein Zertifikat für die Managementschnittstelle, um den Zugriff auf den Grid Manager, den Mandanten-Manager, die Grid-Management-API und die Mandantenmanagement-API zu sichern. Wenn Sie SSO-Vertrauensstellen für StorageGRID in AD FS konfigurieren, verwenden Sie das Serverzertifikat als Signaturzertifikat für StorageGRID-Anforderungen an AD FS.

Falls Sie noch kein benutzerdefiniertes Serverzertifikat für die Managementoberfläche installiert haben, sollten Sie dies jetzt tun. Wenn Sie ein benutzerdefiniertes Serverzertifikat installieren, wird es für alle Administratorknoten verwendet, und Sie können es in allen StorageGRID-Vertrauensstellungen verwenden.


NOTE: Es wird nicht empfohlen, das Standardserverzertifikat eines Admin-Knotens im AD FS-Vertrauensverhältnis zu verwenden. Wenn der Knoten ausfällt und Sie ihn wiederherstellen, wird ein neues Standard-Serverzertifikat generiert. Bevor Sie sich beim wiederhergestellten Knoten anmelden können, müssen Sie das Vertrauensverhältnis der betreffenden Partei in AD FS mit dem neuen Zertifikat aktualisieren.

Sie können auf das Serverzertifikat eines Admin-Knotens zugreifen, indem Sie sich bei der Befehlshülle des Knotens anmelden und auf die zugreifen `/var/local/mgmt-api` Verzeichnis. Ein benutzerdefiniertes Serverzertifikat ist benannt `custom-server.crt`. Das Standardserverzertifikat des Node wird mit benannt `server.crt`.

.Verwandte Informationen
link:controlling-access-through-firewalls.html["Zugriffskontrolle durch Firewalls"]

link:configuring-custom-server-certificate-for-grid-manager-tenant-manager.html["Konfigurieren eines benutzerdefinierten Serverzertifikats für den Grid Manager und den Tenant Manager"]
