---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: In diesem Abschnitt wird beschrieben, wie das StorageGRID System S3-REST-API-Vorgänge für Objekte implementiert. 
---
= Operationen für Objekte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In diesem Abschnitt wird beschrieben, wie das StorageGRID System S3-REST-API-Vorgänge für Objekte implementiert.

* link:using-s3-object-lock.html["Verwenden der S3-Objektsperre"]
* link:using-server-side-encryption.html["Mit Servver-seitiger Verschlüsselung"]
* link:get-object.html["GET Objekt"]
* link:head-object.html["HEAD Objekt"]
* link:post-object-restore.html["WIEDERHERSTELLUNG VON POSTOBJEKTEN"]
* link:put-object.html["PUT Objekt"]
* link:put-object-copy.html["PUT Objekt - Kopieren"]


Die folgenden Bedingungen gelten für alle Objektvorgänge:

* StorageGRID Consistency Controls werden von allen Operationen für Objekte unterstützt, mit Ausnahme der folgenden:
+
** GET Objekt-ACL
** `OPTIONS /`
** LEGALE Aufbewahrung des Objekts EINGEBEN
** AUFBEWAHRUNG von Objekten


* Widersprüchliche Clientanforderungen, wie z. B. zwei Clients, die in denselben Schlüssel schreiben, werden auf „`latest-WINS`“-Basis gelöst. Der Zeitpunkt für die „`latest-WINS` “ -Bewertung basiert auf dem Zeitpunkt, an dem das StorageGRID System eine bestimmte Anfrage abschließt, und nicht auf dem, wenn S3-Clients einen Vorgang starten.
* Alle Objekte in einem StorageGRID-Bucket sind im Eigentum des Bucket-Inhabers. Dies umfasst Objekte, die von einem anonymen Benutzer oder einem anderen Konto erstellt wurden.
* Auf Datenobjekte, die über Swift in das StorageGRID-System aufgenommen werden, kann nicht über S3 zugegriffen werden.


In der folgenden Tabelle wird beschrieben, wie StorageGRID S3-REST-API-Objektvorgänge implementiert.

|===
| Betrieb | Implementierung 


 a| 
Objekt LÖSCHEN
 a| 
Multi-Faktor Authentication (MFA) und Response Header `x-amz-mfa` Werden nicht unterstützt.

Bei der Verarbeitung einer LÖSCHOBJEKTANFORDERUNG versucht StorageGRID, alle Kopien des Objekts sofort von allen gespeicherten Speicherorten zu entfernen. Wenn erfolgreich, gibt StorageGRID sofort eine Antwort an den Client zurück. Falls nicht alle Kopien innerhalb von 30 Sekunden entfernt werden können (z. B. weil ein Standort vorübergehend nicht verfügbar ist), warteschlangen StorageGRID die Kopien zum Entfernen und zeigen dann den Erfolg des Clients an.

*Versionierung*

Um eine bestimmte Version zu entfernen, muss der Anforderer der Bucket-Eigentümer sein und den verwenden `versionId` unterressource. Durch die Verwendung dieser Unterressource wird die Version dauerhaft gelöscht. Wenn der `versionId` Entspricht einer Löschen-Markierung, dem Antwortkopf `x-amz-delete-marker` Wird auf festgelegt `true`.

* Wird ein Objekt ohne gelöscht `versionId` unterressource auf einem Bucket mit Versionsfunktion führt zur Generierung einer Löschmarkierung. Der `versionId` Für die Löschen-Markierung wird mit dem zurückgegeben `x-amz-version-id` Kopfzeile der Antwort und das `x-amz-delete-marker` Der Antwortkopf wird auf festgelegt `true`.
* Wird ein Objekt ohne gelöscht `versionId` unterressource in einem Version suspended Bucket führt es zu einer dauerhaften Löschung einer bereits vorhandenen 'null' Version oder eines 'null' Löschmarker und der Generierung eines neuen 'null' Löschmarker. Der `x-amz-delete-marker` Der Antwortkopf wird auf festgelegt `true`.


*Hinweis*: In bestimmten Fällen können für ein Objekt mehrere Löschen-Marker vorhanden sein.



 a| 
LÖSCHEN Sie mehrere Objekte
 a| 
Multi-Faktor Authentication (MFA) und Response Header `x-amz-mfa` Werden nicht unterstützt.

In derselben Anforderungsmeldung können mehrere Objekte gelöscht werden.



 a| 
Objekt-Tagging LÖSCHEN
 a| 
Verwendet das `tagging` unterressource, um alle Tags aus einem Objekt zu entfernen. Wird mit dem gesamten Amazon S3-REST-API-Verhalten implementiert.

*Versionierung*

Wenn der `versionId` Der Abfrageparameter wird in der Anforderung nicht angegeben. Der Vorgang löscht alle Tags von der neuesten Version des Objekts in einem versionierten Bucket. Wenn die aktuelle Version des Objekts ein Löschen-Marker ist, wird mit dem ein Status „`MethodNotAllowed`“ zurückgegeben `x-amz-delete-marker` Antwortkopfzeile auf gesetzt `true`.



 a| 
GET Objekt
 a| 
link:get-object.html["GET Objekt"]



 a| 
GET Objekt-ACL
 a| 
Wenn für das Konto die erforderlichen Zugangsdaten bereitgestellt werden, gibt der Vorgang eine positive Antwort und die ID, DisplayName und die Berechtigung des Objekteigentümers zurück und gibt an, dass der Eigentümer vollen Zugriff auf das Objekt hat.



 a| 
HOLD-Aufbewahrung für Objekte
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Verwenden der S3-Objektsperre"]



 a| 
Aufbewahrung von Objekten
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Verwenden der S3-Objektsperre"]



 a| 
GET Objekt-Tagging
 a| 
Verwendet das `tagging` unterressource, um alle Tags für ein Objekt zurückzugeben. Wird mit dem gesamten Amazon S3-REST-API-Verhalten implementiert

*Versionierung*

Wenn der `versionId` Der Abfrageparameter wird in der Anforderung nicht angegeben. Der Vorgang gibt alle Tags der neuesten Version des Objekts in einem versionierten Bucket zurück. Wenn die aktuelle Version des Objekts ein Löschen-Marker ist, wird mit dem ein Status „`MethodNotAllowed`“ zurückgegeben `x-amz-delete-marker` Antwortkopfzeile auf gesetzt `true`.



 a| 
HEAD Objekt
 a| 
link:head-object.html["HEAD Objekt"]



 a| 
WIEDERHERSTELLUNG VON POSTOBJEKTEN
 a| 
link:post-object-restore.html["WIEDERHERSTELLUNG VON POSTOBJEKTEN"]



 a| 
PUT Objekt
 a| 
link:put-object.html["PUT Objekt"]



 a| 
PUT Objekt - Kopieren
 a| 
link:put-object-copy.html["PUT Objekt - Kopieren"]



 a| 
LEGALE Aufbewahrung des Objekts EINGEBEN
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Verwenden der S3-Objektsperre"]



 a| 
AUFBEWAHRUNG von Objekten
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Verwenden der S3-Objektsperre"]



 a| 
PUT Objekt-Tagging
 a| 
Verwendet das `tagging` unterressource, um einem vorhandenen Objekt einen Satz von Tags hinzuzufügen. Wird mit dem gesamten Amazon S3-REST-API-Verhalten implementiert

*Tag-Updates und Aufnahmeverhalten*

Wenn Sie PUT Objekt-Tagging zum Aktualisieren der Tags eines Objekts verwenden, nimmt StorageGRID das Objekt nicht erneut auf. Das bedeutet, dass die in der übereinstimmenden ILM-Regel angegebene Option für das Aufnahmeverhalten nicht verwendet wird. Sämtliche durch das Update ausgelösten Änderungen an der Objektplatzierung werden vorgenommen, wenn ILM durch normale ILM-Prozesse im Hintergrund neu bewertet wird.

Das bedeutet, dass, wenn die ILM-Regel die strikte Option für das Ingest-Verhalten verwendet, keine Maßnahmen ergriffen werden, wenn die erforderlichen Objektplatzierungen nicht durchgeführt werden können (z. B. weil ein neu benötigter Speicherort nicht verfügbar ist). Das aktualisierte Objekt behält seine aktuelle Platzierung bei, bis die erforderliche Platzierung möglich ist.

* Konflikte lösen*

Widersprüchliche Clientanforderungen, wie z. B. zwei Clients, die in denselben Schlüssel schreiben, werden auf „`latest-WINS`“-Basis gelöst. Der Zeitpunkt für die „`latest-WINS` “ -Bewertung basiert auf dem Zeitpunkt, an dem das StorageGRID System eine bestimmte Anfrage abschließt, und nicht auf dem, wenn S3-Clients einen Vorgang starten.

*Versionierung*

Wenn der `versionId` Der Abfrageparameter wird in der Anforderung nicht angegeben, und der Vorgang fügt Tags zur aktuellen Version des Objekts in einem versionierten Bucket hinzu. Wenn die aktuelle Version des Objekts ein Löschen-Marker ist, wird mit dem ein Status „`MethodNotAllowed`“ zurückgegeben `x-amz-delete-marker` Antwortkopfzeile auf gesetzt `true`.

|===
.Verwandte Informationen
link:consistency-controls.html["Konsistenzkontrollen"]

link:s3-operations-tracked-in-audit-logs.html["S3-Vorgänge werden in den Audit-Protokollen protokolliert"]
