---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Unterstützte Vorgänge und Einschränkungen durch S3-REST-API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das StorageGRID System implementiert die Simple Storage Service API (API Version 2006-03-01) mit Unterstützung der meisten Operationen und mit einigen Einschränkungen. Wenn Sie S3 REST-API-Client-Applikationen integrieren, sind die Implementierungsdetails bekannt.

Das StorageGRID System unterstützt sowohl Virtual-Hosted-Style-Anforderungen als auch Anforderungen im Pfadstil.

* link:authenticating-requests.html["Authentifizierung von Anforderungen"]
* link:operations-on-the-service.html["Betrieb auf dem Service"]
* link:operations-on-buckets.html["Operationen auf Buckets"]
* link:custom-operations-on-buckets.html["Benutzerdefinierte Vorgänge für Buckets"]
* link:operations-on-objects.html["Operationen für Objekte"]
* link:operations-for-multipart-uploads.html["Vorgänge für mehrteilige Uploads"]
* link:error-responses.html["Fehlerantworten"]




== Umgang mit Daten

Die StorageGRID Implementierung der S3-REST-API unterstützt nur gültige HTTP-Datumsformate.

Das StorageGRID-System unterstützt nur gültige HTTP-Datumsformate für alle Header, die Datumswerte akzeptieren. Der Zeitbereich des Datums kann im Greenwich Mean Time (GMT)-Format oder im UTC-Format (Universal Coordinated Time) ohne Zeitzonenversatz angegeben werden (+0000 muss angegeben werden). Wenn Sie die einschließen `x-amz-date` Kopfzeile in Ihrer Anfrage, es überschreibt alle Werte, die in der Kopfzeile der Datumsanforderung angegeben sind. Bei Verwendung von AWS Signature Version 4, das `x-amz-date` Die Kopfzeile muss in der signierten Anforderung vorhanden sein, da die Datumsüberschrift nicht unterstützt wird.



== Allgemeine Anfragemöpfe

Das StorageGRID System unterstützt gemeinsame Anfrageheader, die von der _Simple Storage Service API Reference_ definiert wurden, mit einer Ausnahme.

|===
| Kopfzeile der Anfrage | Implementierung 


 a| 
Autorisierung
 a| 
Vollständige Unterstützung für AWS Signature Version 2

Unterstützung für AWS Signature Version 4, mit folgenden Ausnahmen:

* Der SHA256-Wert wird für den Körper der Anforderung nicht berechnet. Der vom Benutzer eingereichte Wert wird ohne Validierung angenommen, als ob der Wert `UNSIGNED-PAYLOAD` War für die vorgesehen `x-amz-content-sha256` Kopfzeile.




 a| 
X-amz-Sicherheits-Token
 a| 
Nicht implementiert. Kehrt Zurück `XNotImplemented`.

|===


== Allgemeine Antwortkopfzeilen

Das StorageGRID System unterstützt alle gängigen Antwortheader, die durch die _Simple Storage Service API Reference_ definiert wurden. Eine Ausnahme bilden die Antwort.

|===
| Kopfzeile der Antwort | Implementierung 


 a| 
X-amz-id-2
 a| 
Nicht verwendet

|===
.Verwandte Informationen
http://["Amazon Web Services (AWS) Dokumentation: Amazon Simple Storage Service API Reference"]
