---
permalink: monitor/comparing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: alerts, alarms, comparing alerts and alarms 
summary: Es gibt eine Reihe von Ähnlichkeiten zwischen dem Alarmsystem und dem alten Alarmsystem, aber das Alarmsystem bietet erhebliche Vorteile und ist einfacher zu bedienen. 
---
= Vergleichen von Meldungen und Alarmen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt eine Reihe von Ähnlichkeiten zwischen dem Alarmsystem und dem alten Alarmsystem, aber das Alarmsystem bietet erhebliche Vorteile und ist einfacher zu bedienen.

In der folgenden Tabelle erfahren Sie, wie Sie ähnliche Vorgänge ausführen.

|===
|  | Meldungen | Alarme (Altsystem) 


 a| 
Wie sehe ich, welche Alarme oder Alarme aktiv sind?
 a| 
* Klicken Sie im Dashboard auf den Link *Aktuelle Alarme*.
* Klicken Sie auf der Seite *Nodes* > *Übersicht* auf den Hinweis.
* Wählen Sie *Alarme* > *Aktuell*.


link:viewing-current-alerts.html["Anzeigen aktueller Meldungen"]
 a| 
* Klicken Sie im Dashboard auf den Link *Legacy-Alarme*.
* Wählen Sie *Support* > *Alarme (alt)* > *Aktuelle Alarme*.


link:viewing-legacy-alarms.html["Anzeigen von Legacy-Alarmen"]



 a| 
Was bewirkt, dass eine Meldung oder eine Warnung ausgelöst wird?
 a| 
Alarme werden ausgelöst, wenn ein Prometheus-Ausdruck in einer Alarmregel für die spezifische Triggerbedingung und -Dauer als wahr bewertet wird.

link:managing-alerts.html["Anzeigen von Meldungsregeln"]
 a| 
Alarme werden ausgelöst, wenn ein StorageGRID-Attribut einen Schwellenwert erreicht.

link:managing-alarms.html["Alarmauslöselogik (Älteres System)"]



 a| 
Wie kann ich das zugrunde liegende Problem lösen, wenn eine Meldung oder ein Alarm ausgelöst wird?
 a| 
Die empfohlenen Aktionen für eine Warnmeldung sind in E-Mail-Benachrichtigungen enthalten und stehen auf den Alerts-Seiten im Grid Manager zur Verfügung.

Falls erforderlich, werden weitere Informationen in der StorageGRID-Dokumentation bereitgestellt.

link:alerts-reference.html["Alerts Referenz"]
 a| 
Sie können sich über einen Alarm informieren, indem Sie auf den Attributnamen klicken. Alternativ können Sie in der StorageGRID-Dokumentation nach einem Alarmcode suchen.

link:alarms-reference.html["Alarmreferenz (Altsystem)"]



 a| 
Wo kann eine Liste der Warnungen oder Alarme gelöst werden?
 a| 
* Klicken Sie auf dem Dashboard auf den Link * Kürzlich aufgelöste Warnmeldungen*.
* Wählen Sie *Alarme* > *Aufgelöst*.


link:viewing-resolved-alerts.html["Anzeigen gelöster Warnmeldungen"]
 a| 
Wählen Sie *Support* > *Alarme (alt)* > *Historische Alarme*.

link:managing-alarms.html["Überprüfung historischer Alarme und Alarmfrequenz (Altsystem)"]



 a| 
Wo kann ich die Einstellungen verwalten?
 a| 
Wählen Sie *Alarme*. Verwenden Sie anschließend die Optionen im Menü Meldungen.

link:managing-alerts.html["Verwalten von Meldungen"]
 a| 
Wählen Sie *Support*. Verwenden Sie dann die Optionen im Abschnitt *Alarme (alt)* des Menüs.

link:managing-alarms.html["Verwalten von Alarmen (Altsystem)"]



 a| 
Welche Benutzergruppenberechtigungen brauche ich?
 a| 
* Jeder, der sich beim Grid Manager anmelden kann, kann aktuelle und behobene Warnmeldungen anzeigen.
* Sie müssen über die Berechtigung zum Verwalten von Warnungen verfügen, um Stille, Warnmeldungen und Alarmregeln zu verwalten.


link:../admin/index.html["StorageGRID verwalten"]
 a| 
* Jeder, der sich beim Grid Manager anmelden kann, kann ältere Alarme anzeigen.
* Sie müssen über die Berechtigung Alarme quittieren verfügen, um Alarme zu quittieren.
* Zur Verwaltung globaler Alarme und E-Mail-Benachrichtigungen müssen Sie sowohl über die Seitenkonfiguration der Grid-Topologie als auch über andere Grid-Konfigurationen verfügen.


link:../admin/index.html["StorageGRID verwalten"]



 a| 
Wie managt ich E-Mail-Benachrichtigungen?
 a| 
Wählen Sie *Alarme* > *E-Mail-Einrichtung*.

*Hinweis:* Da Alarme und Alarme unabhängige Systeme sind, wird das E-Mail-Setup für Alarm- und AutoSupport-Benachrichtigungen nicht für Benachrichtigungen verwendet. Sie können jedoch denselben E-Mail-Server für alle Benachrichtigungen verwenden.

link:managing-alerts.html["Verwalten von Warnmeldungen"]
 a| 
Wählen Sie *Support* > *Alarme (alt)* > *Legacy E-Mail-Einrichtung*. link:managing-alarms.html["Konfigurieren von Benachrichtigungen für Alarme (Legacy-System)"]



 a| 
Wie verwalte ich SNMP Benachrichtigungen?
 a| 
Wählen Sie *Konfiguration* > *Überwachung* > *SNMP-Agent*. link:using-snmp-monitoring.html["Verwendung von SNMP-Überwachung"]
 a| 
Wählen Sie *Konfiguration* > *Überwachung* > *SNMP-Agent*. link:using-snmp-monitoring.html["Verwendung von SNMP-Überwachung"]

*Hinweis*: SNMP-Benachrichtigungen werden nicht für jeden Alarm oder Alarm Schweregrad gesendet.

link:alarms-that-generate-snmp-notifications.html["Warnmeldungen, die SNMP-Benachrichtigungen generieren (Legacy-System)"]



 a| 
Wie kontrolliere ich, wer Benachrichtigungen erhält?
 a| 
. Wählen Sie *Alarme* > *E-Mail-Einrichtung*.
. Geben Sie im Abschnitt *Empfänger* eine E-Mail-Adresse für jede E-Mail-Liste oder Person ein, die eine E-Mail erhalten soll, wenn eine Benachrichtigung erfolgt.


link:managing-alerts.html["Einrichten von E-Mail-Benachrichtigungen für Meldungen"]
 a| 
. Wählen Sie *Support* > *Alarme (alt)* > *Legacy E-Mail-Einrichtung*.
. Mailingliste wird erstellt.
. Wählen Sie *Benachrichtigungen*.
. Wählen Sie die Mailingliste aus.


link:managing-alarms.html["Erstellen von Mailinglisten für Alarmbenachrichtigungen (Altsystem)"]

link:managing-alarms.html["Konfigurieren von E-Mail-Benachrichtigungen für Alarme (Altsystem)"]



 a| 
Welche Admin Nodes senden Benachrichtigungen?
 a| 
Ein einziger Admin-Node (der „`bevorzugte Absender`“).

link:../admin/index.html["StorageGRID verwalten"]
 a| 
Ein einziger Admin-Node (der „`bevorzugte Absender`“).

link:../admin/index.html["StorageGRID verwalten"]



 a| 
Wie kann ich einige Benachrichtigungen unterdrücken?
 a| 
. Wählen Sie *Alarme* > *Stille*.
. Wählen Sie die Alarmregel aus, die stummschalten soll.
. Geben Sie eine Dauer für die Stille an.
. Wählen Sie den Schweregrad der Warnmeldung aus, den Sie stummschalten möchten.
. Wählen Sie diese Option aus, um die Stille auf das gesamte Raster, einen einzelnen Standort oder einen einzelnen Knoten anzuwenden.


*Hinweis*: Wenn Sie den SNMP-Agent aktiviert haben, unterdrücken Stille auch SNMP-Traps und informieren.

link:managing-alerts.html["Stummschalten von Warnmeldungen"]
 a| 
. Wählen Sie *Support* > *Alarme (alt)* > *Legacy E-Mail-Einrichtung*.
. Wählen Sie *Benachrichtigungen*.
. Wählen Sie eine Mailingliste aus, und wählen Sie *unterdrücken*.


link:managing-alarms.html["Unterdrückung von Alarmmeldungen für eine Mailingliste (Legacy-System)"]



 a| 
Wie kann ich alle Benachrichtigungen unterdrücken?
 a| 
Wählen Sie *Alarme* > *Stille* und dann *Alle Regeln*.

*Hinweis*: Wenn Sie den SNMP-Agent aktiviert haben, unterdrücken Stille auch SNMP-Traps und informieren.

link:managing-alerts.html["Stummschalten von Warnmeldungen"]
 a| 
. Wählen Sie *Konfiguration* > *Systemeinstellungen* > *Anzeigeoptionen*.
. Aktivieren Sie das Kontrollkästchen *Benachrichtigung Alle unterdrücken*.


*Hinweis*: Das Unterdrückung von E-Mail-Benachrichtigungen systemweit unterdrückt auch ereignisgesteuerte AutoSupport-E-Mails.

link:managing-alarms.html["Systemweite Unterdrückung von E-Mail-Benachrichtigungen"]



 a| 
Wie kann ich die Bedingungen und Trigger anpassen?
 a| 
. Wählen Sie *Alarme* > *Warnregeln*.
. Wählen Sie eine Standardregel zum Bearbeiten aus, oder wählen Sie *benutzerdefinierte Regel erstellen*.


link:managing-alerts.html["Bearbeiten einer Meldungsregel"]

link:managing-alerts.html["Erstellen benutzerdefinierter Warnungsregeln"]
 a| 
. Wählen Sie *Support* > *Alarme (alt)* > *Globale Alarme*.
. Erstellen Sie einen globalen benutzerdefinierten Alarm, um einen Standardalarm zu überschreiben oder ein Attribut zu überwachen, das keinen Standardalarm hat.


link:managing-alarms.html["Erstellen von globalen benutzerdefinierten Alarmen (Legacy-System)"]



 a| 
Wie deaktiviere ich eine einzelne Warnung oder einen einzelnen Alarm?
 a| 
. Wählen Sie *Alarme* > *Warnregeln*.
. Wählen Sie die Regel aus, und klicken Sie auf *Regel bearbeiten*.
. Deaktivieren Sie das Kontrollkästchen *aktiviert*.


link:managing-alerts.html["Deaktivieren einer Meldungsregel"]
 a| 
. Wählen Sie *Support* > *Alarme (alt)* > *Globale Alarme*.
. Wählen Sie die Regel aus, und klicken Sie auf das Symbol Bearbeiten.
. Deaktivieren Sie das Kontrollkästchen *aktiviert*.


link:managing-alarms.html["Deaktivieren eines Standardalarms (älteres System)"]

link:managing-alarms.html["Deaktivieren von globalen benutzerdefinierten Alarmen (Legacy-System)"]

|===