---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: Nach der Wiederherstellung eines Appliance Storage Node müssen Sie überprüfen, ob der gewünschte Status des Appliance Storage Node auf „Online“ gesetzt ist, und vergewissern Sie sich, dass der Status bei jedem Neustart des Storage Node-Servers standardmäßig online ist. 
---
= Überprüfen des Speicherstatus nach der Wiederherstellung eines Appliance-Speicherknoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Wiederherstellung eines Appliance Storage Node müssen Sie überprüfen, ob der gewünschte Status des Appliance Storage Node auf „Online“ gesetzt ist, und vergewissern Sie sich, dass der Status bei jedem Neustart des Storage Node-Servers standardmäßig online ist.

.Was Sie benötigen
* Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.
* Der Speicherknoten wurde wiederhergestellt und die Datenwiederherstellung ist abgeschlossen.


.Schritte
. Wählen Sie *Support* > *Tools* > *Grid Topology* Aus.
. Überprüfen Sie die Werte von *wiederhergestellten Speicherknoten* *LDR* *Storage* *Speicherzustand -- gewünscht* und *Speicherzustand -- Strom*.
+
Der Wert beider Attribute sollte Online sein.

. Wenn der Speicherstatus -- gewünscht auf schreibgeschützt eingestellt ist, führen Sie die folgenden Schritte aus:
+
.. Klicken Sie auf die Registerkarte *Konfiguration*.
.. Wählen Sie aus der Dropdown-Liste *Storage State -- gewünschte* die Option *Online* aus.
.. Klicken Sie Auf *Änderungen Übernehmen*.
.. Klicken Sie auf die Registerkarte *Übersicht* und bestätigen Sie, dass die Werte von *Speicherzustand -- gewünscht* und *Speicherzustand -- Aktuell* auf Online aktualisiert werden.



