---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: storagegrid, ip address, configure ip address, configuring ip address, network configuration, network configure, network configuring 
summary: Sie können eine Netzwerkkonfiguration durchführen, indem Sie IP-Adressen für Grid-Nodes mithilfe des Tools IP ändern konfigurieren. 
---
= IP-Adressen werden konfiguriert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Netzwerkkonfiguration durchführen, indem Sie IP-Adressen für Grid-Nodes mithilfe des Tools IP ändern konfigurieren.

Sie müssen das Change IP-Tool verwenden, um die meisten Änderungen an der Netzwerkkonfiguration vorzunehmen, die ursprünglich während der Grid-Implementierung festgelegt wurde. Manuelle Änderungen unter Verwendung von standardmäßigen Linux-Netzwerkbefehlen und Dateien werden möglicherweise nicht an allen StorageGRID-Diensten weitergegeben. Dabei bleiben Upgrades, Neustarts oder Recovery-Verfahren für Knoten nicht erhalten.


NOTE: Wenn Sie die Grid-Netzwerk-IP-Adresse für alle Knoten im Raster ändern möchten, verwenden Sie das spezielle Verfahren für Grid-weite Änderungen.

link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["Ändern der IP-Adressen für alle Nodes im Grid"]


NOTE: Wenn Sie nur Änderungen an der Netznetzwerksubnetz-Liste vornehmen, verwenden Sie den Grid-Manager, um die Netzwerkkonfiguration hinzuzufügen oder zu ändern. Verwenden Sie andernfalls das Change IP-Tool, wenn der Grid Manager aufgrund eines Netzwerkkonfigurationsproblem nicht erreichbar ist, oder Sie führen gleichzeitig eine Änderung des Grid Network Routing und andere Netzwerkänderungen durch.


IMPORTANT: Das IP-Änderungsverfahren kann eine UnterbrechungsMaßnahme sein. Teile des Rasters sind möglicherweise erst verfügbar, wenn die neue Konfiguration angewendet wird.

* Ethernet-Schnittstellen*

Die eth0 zugewiesene IP-Adresse ist immer die Grid-Netzwerk-IP-Adresse des Grid-Node. Die eth1 zugewiesene IP-Adresse ist immer die Admin-Netzwerk-IP-Adresse des Grid-Node. Die eth2 zugewiesene IP-Adresse ist immer die Client-Netzwerk-IP-Adresse des Grid-Node.

Beachten Sie, dass auf einigen Plattformen, z. B. StorageGRID Appliances, eth0, eth1 und eth2, aggregierte Schnittstellen bestehen, die aus untergeordneten Bridges oder Bindungen von physischen oder VLAN-Schnittstellen bestehen. Auf diesen Plattformen wird auf der Registerkarte *SSM* *Ressourcen* die Grid-, Admin- und Client-Netzwerk-IP-Adresse angezeigt, die anderen Schnittstellen zusätzlich zu eth0, eth1 oder eth2 zugewiesen ist.

*DHCP*

Sie können DHCP nur während der Bereitstellungsphase einrichten. Sie können DHCP während der Konfiguration nicht einrichten. Sie müssen die Änderungsverfahren für die IP-Adresse verwenden, wenn Sie IP-Adressen, Subnetzmaske und Standard-Gateways für einen Grid-Node ändern möchten. Wenn Sie das Tool IP ändern verwenden, werden DHCP-Adressen statisch.

*Hochverfügbarkeitsgruppen*

* Die Client-Netzwerk-IP-Adresse kann nicht außerhalb des Subnetzes einer HA-Gruppe geändert werden, die in der Client-Netzwerkschnittstelle konfiguriert ist.
* Sie können die IP-Adresse des Client-Netzwerks nicht in den Wert einer vorhandenen virtuellen IP-Adresse ändern, die von einer HA-Gruppe zugewiesen wurde, die in der Client-Netzwerkschnittstelle konfiguriert ist.
* Die Grid-Netzwerk-IP-Adresse kann nicht außerhalb des Subnetzes einer auf der Grid-Netzwerkschnittstelle konfigurierten HA-Gruppe geändert werden.
* Sie können die IP-Adresse des Grid-Netzwerks nicht in den Wert einer vorhandenen virtuellen IP-Adresse ändern, die von einer HA-Gruppe zugewiesen wurde, die auf der Grid-Netzwerkschnittstelle konfiguriert ist.


.Wahlmöglichkeiten
* link:changing-nodes-network-configuration.html["Ändern der Netzwerkkonfiguration eines Node"]
* link:adding-to-or-changing-subnet-lists-on-admin-network.html["Hinzufügen oder Ändern von Subnetzlisten im Admin-Netzwerk"]
* link:adding-to-or-changing-subnet-lists-on-grid-network.html["Hinzufügen oder Ändern von Subnetzlisten im Grid-Netzwerk"]
* link:linux-adding-interfaces-to-existing-node.html["Linux: Hinzufügen von Schnittstellen zu einem vorhandenen Node"]
* link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["Ändern der IP-Adressen für alle Nodes im Grid"]

