---
permalink: maintain/considerations-for-decommissioning-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: Bevor Sie dieses Verfahren zur Deaktivierung von einem oder mehreren Nodes starten, müssen Sie die Auswirkungen des Entfernens der einzelnen Node verstehen. Bei der erfolgreichen Ausmusterung eines Node werden seine Services deaktiviert und der Node wird automatisch heruntergefahren. 
---
= Überlegungen für die Deaktivierung von Grid-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie dieses Verfahren zur Deaktivierung von einem oder mehreren Nodes starten, müssen Sie die Auswirkungen des Entfernens der einzelnen Node verstehen. Bei der erfolgreichen Ausmusterung eines Node werden seine Services deaktiviert und der Node wird automatisch heruntergefahren.

Sie können einen Node nicht stilllegen, wenn Sie dies tun, bleibt die StorageGRID in einem ungültigen Status. Folgende Regeln werden durchgesetzt:

* Sie können den primären Admin-Node nicht stilllegen.
* Sie können Archiv-Knoten nicht stilllegen.
* Sie können einen Admin-Node oder einen Gateway-Node nicht stilllegen, wenn eine seiner Netzwerkschnittstellen Teil einer HA-Gruppe (High Availability, Hochverfügbarkeit) ist.
* Sie können einen Speicherknoten nicht stilllegen, wenn sich dessen Entfernung auf das ADC-Quorum auswirkt.
* Sie können einen Storage-Node nicht stilllegen, wenn er für die aktive ILM-Richtlinie erforderlich ist.
* Sie sollten nicht mehr als 10 Storage-Nodes in einem einzigen Decommission-Node-Verfahren außer Betrieb nehmen.
* Sie können einen verbundenen Knoten nicht stilllegen, wenn in Ihrem Grid keine getrennten Knoten enthalten sind (Knoten, deren Zustand unbekannt oder administrativ ausgefallen ist). Sie müssen zunächst die getrennten Nodes außer Betrieb nehmen oder wiederherstellen.
* Wenn Ihr Grid mehrere getrennte Nodes enthält, muss die Software gleichzeitig außer Betrieb genommen werden. Dadurch steigt das Risiko unerwarteter Ergebnisse.
* Wenn ein nicht getrennter Knoten nicht entfernt werden kann (z. B. ein Speicherknoten, der für das ADC-Quorum benötigt wird), kann kein anderer nicht getrennter Knoten entfernt werden.
* Wenn Sie eine ältere Appliance durch eine neuere Appliance ersetzen möchten, sollten Sie eventuell das Klonverfahren für den Appliance-Node verwenden, anstatt den alten Node abzubauen und den neuen Node zu einer Erweiterung hinzuzufügen.
+
link:appliance-node-cloning.html["Klonen von Appliance-Nodes"]




IMPORTANT: Entfernen Sie die virtuelle Maschine oder andere Ressourcen eines Grid-Node erst, wenn Sie dazu aufgefordert werden, dies in Stilllegen-Verfahren zu tun.
