---
permalink: maintain/recovering-from-non-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, non-primary admin node failure 
summary: 'Sie müssen die folgenden Aufgaben durchführen, um nach einem Ausfall eines nicht primären Admin-Knotens wiederherzustellen. Ein Admin-Node hostet den Configuration Management Node \(CMN\)-Dienst und ist als primärer Admin-Node bekannt. Obwohl Sie mehrere Admin-Nodes haben können, enthält jedes StorageGRID-System nur einen primären Admin-Node. Alle anderen Admin-Nodes sind nicht primäre Admin-Nodes.' 
---
= Wiederherstellung nach Ausfällen eines Admin-Knotens außerhalb des primären Standorts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die folgenden Aufgaben durchführen, um nach einem Ausfall eines nicht primären Admin-Knotens wiederherzustellen. Ein Admin-Node hostet den Configuration Management Node (CMN)-Service und ist als primärer Admin-Node bekannt. Obwohl Sie mehrere Admin-Nodes haben können, enthält jedes StorageGRID-System nur einen primären Admin-Node. Alle anderen Admin-Nodes sind nicht primäre Admin-Nodes.

.Verwandte Informationen
link:../sg100-1000/index.html["SG100  SG1000 Services-Appliances"]

.Schritte
* link:copying-audit-logs-from-failed-non-primary-admin-node.html["Prüfprotokolle werden vom fehlgeschlagenen nicht-primären Admin-Node kopiert"]
* link:replacing-non-primary-admin-node.html["Ersetzen eines nicht-primären Admin-Knotens"]
* link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Wählen Sie Wiederherstellung starten, um einen nicht primären Admin-Node zu konfigurieren"]
* link:restoring-audit-log-on-recovered-non-primary-admin-node.html["Wiederherstellen des Prüfprotokolls auf dem wiederhergestellten nicht-primären Admin-Knoten"]
* link:resetting-preferred-sender-on-recovered-non-primary-admin-node.html["Zurücksetzen des bevorzugten Senders auf dem wiederhergestellten nicht-primären Admin-Node"]
* link:restoring-admin-node-database-non-primary-admin-node.html["Wiederherstellen der Admin-Knoten-Datenbank bei der Wiederherstellung eines nicht-primären Admin-Knotens"]
* link:restoring-prometheus-metrics-non-primary-admin-node.html["Wiederherstellen von Prometheus-Kennzahlen bei der Wiederherstellung eines nicht primären Admin-Nodes"]

