---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 'Sie müssen einen bestimmten Satz von Aufgaben ausführen, um nach einem Ausfall eines primären Admin-Knotens wiederherstellen zu können. Der primäre Admin-Node hostet den Configuration Management Node \(CMN\)-Dienst für das Grid.' 
---
= Wiederherstellung nach Ausfällen des primären Admin-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen einen bestimmten Satz von Aufgaben ausführen, um nach einem Ausfall eines primären Admin-Knotens wiederherstellen zu können. Der primäre Admin-Node hostet den Configuration Management Node (CMN)-Service für das Grid.

.Über diese Aufgabe
Ein fehlgeschlagener primärer Admin-Node sollte umgehend ersetzt werden. Der Configuration Management Node (CMN)-Dienst auf dem primären Admin-Node ist für die Ausgabe von Objektkennungen für das Grid verantwortlich. Diese Kennungen werden Objekten bei ihrer Aufnahme zugewiesen. Neue Objekte können erst dann aufgenommen werden, wenn Identifikatoren verfügbar sind. Die Objektaufnahme kann fortgesetzt werden, während das CMN nicht verfügbar ist, da die Identifikatoren ungefähr einen Monat im Grid zwischengespeichert werden. Nachdem jedoch die gecachten Kennungen erschöpft sind, können keine neuen Objekte hinzugefügt werden.


IMPORTANT: Sie müssen einen fehlerhaften primären Administrator-Node innerhalb von etwa einem Monat reparieren oder ersetzen. Andernfalls kann das Grid die Aufnahme neuer Objekte verlieren. Der genaue Zeitraum hängt von der Geschwindigkeit der Objekterfassung ab: Wenn Sie eine genauere Bewertung des Zeitrahmens für Ihr Grid benötigen, wenden Sie sich an den technischen Support.

.Schritte
* link:copying-audit-logs-from-failed-primary-admin-node.html["Prüfprotokolle werden vom fehlgeschlagenen primären Admin-Node kopiert"]
* link:replacing-primary-admin-node.html["Ersetzen des primären Admin-Knotens"]
* link:configuring-replacement-primary-admin-node.html["Konfigurieren des primären Ersatzadministratorknotens"]
* link:restoring-audit-log-on-recovered-primary-admin-node.html["Wiederherstellen des Prüfprotokolls auf dem wiederhergestellten primären Administrator-Knoten"]
* link:resetting-preferred-sender-on-recovered-primary-admin-node.html["Zurücksetzen des bevorzugten Senders auf dem wiederhergestellten primären Admin-Knoten"]
* link:restoring-admin-node-database-primary-admin-node.html["Wiederherstellen der Admin-Knoten-Datenbank bei der Wiederherstellung eines primären Admin-Knotens"]
* link:restoring-prometheus-metrics-primary-admin-node.html["Wiederherstellen von Prometheus-Kennzahlen bei der Wiederherstellung eines primären Admin-Knotens"]

