---
permalink: maintain/resetting-preferred-sender-on-recovered-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, non-primary admin node, reset preferred sender, resetting preferred sender 
summary: Wenn der nicht-primäre Admin-Node, den Sie wiederherstellen, derzeit als bevorzugter Absender von Warnmeldungen, Alarmbenachrichtigungen und AutoSupport-Meldungen eingestellt ist, müssen Sie diese Einstellung im StorageGRID-System neu konfigurieren. 
---
= Zurücksetzen des bevorzugten Senders auf dem wiederhergestellten nicht-primären Admin-Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der nicht-primäre Admin-Node, den Sie wiederherstellen, derzeit als bevorzugter Absender von Warnmeldungen, Alarmbenachrichtigungen und AutoSupport-Meldungen eingestellt ist, müssen Sie diese Einstellung im StorageGRID-System neu konfigurieren.

.Was Sie benötigen
* Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.
* Sie müssen über spezifische Zugriffsberechtigungen verfügen.
* Der wiederhergestellte Admin-Node muss installiert und ausgeführt werden.


.Schritte
. Wählen Sie *Konfiguration* > *Systemeinstellungen* > *Anzeigeoptionen*.
. Wählen Sie den wiederhergestellten Admin-Knoten aus der Dropdown-Liste *bevorzugter Absender* aus.
. Klicken Sie Auf *Änderungen Übernehmen*.


.Verwandte Informationen
link:../admin/index.html["StorageGRID verwalten"]
