---
permalink: sg5700/maintaining-sg5700-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Möglicherweise müssen Sie auf dem E2800 Controller die SANtricity OS Software aktualisieren, die Ethernet-Link-Konfiguration des E5700SG Controllers ändern, den E2800 Controller oder den E5700SG Controller austauschen oder bestimmte Komponenten ersetzen. Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde. 
---
= Warten der SG5700 Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie auf dem E2800 Controller die SANtricity OS Software aktualisieren, die Ethernet-Link-Konfiguration des E5700SG Controllers ändern, den E2800 Controller oder den E5700SG Controller austauschen oder bestimmte Komponenten ersetzen. Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde.

.Schritte
* link:placing-appliance-into-maintenance-mode.html["Versetzen einer Appliance in den Wartungsmodus"]
* link:upgrading-santricity-os-on-storage-controller.html["Aktualisieren des SANtricity OS auf dem Storage Controller"]
* link:upgrading-drive-firmware-using-santricity-system-manager.html["Aktualisieren der Laufwerk-Firmware mit SANtricity System Manager"]
* link:replacing-e2800-controller.html["Austausch des E2800 Controllers"]
* link:replacing-e5700sg-controller.html["Austauschen des E5700SG-Controllers"]
* link:replacing-other-hardware-components-sg5700.html["Austausch anderer Hardwarekomponenten"]
* link:changing-link-configuration-of-e5700sg-controller.html["Ändern der Link-Konfiguration des E5700SG-Controllers"]
* link:changing-mtu-setting.html["Ändern der MTU-Einstellung"]
* link:checking-dns-server-configuration.html["Überprüfen der DNS-Serverkonfiguration"]
* link:monitoring-node-encryption-in-maintenance-mode.html["Monitoring der Node-Verschlüsselung im Wartungsmodus"]

