---
permalink: sg5700/preparing-for-installation.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, installation, preparation, get ready, prepare 
summary: Die Vorbereitung der Installation einer StorageGRID Appliance umfasst die Vorbereitung des Standorts und den Erwerb aller erforderlichen Hardware, Kabel und Tools. Außerdem sollten Sie IP-Adressen und Netzwerkinformationen erfassen. 
---
= Installation wird vorbereitet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Vorbereitung der Installation einer StorageGRID Appliance umfasst die Vorbereitung des Standorts und den Erwerb aller erforderlichen Hardware, Kabel und Tools. Außerdem sollten Sie IP-Adressen und Netzwerkinformationen erfassen.

.Schritte
* link:preparing-site-sg5700.html["Vorbereiten des Standorts (SG5700)"]
* link:unpacking-boxes-sg5700.html["Auspacken der Boxen (SG5700)"]
* link:obtaining-additional-equipment-and-tools-sg5700.html["Zusätzliche Ausrüstung und Tools (SG5700)"]
* link:web-browser-requirements.html["Anforderungen an einen Webbrowser"]
* link:reviewing-appliance-network-connections-sg5700.html["Überprüfen von Appliance-Netzwerkverbindungen"]
* link:gathering-installation-information-sg5700.html["Sammeln von Installationsinformationen (SG5700)"]

