---
permalink: sg5700/upgrading-santricity-os-on-storage-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Um die optimale Funktion des Storage Controllers sicherzustellen, müssen Sie auf die neueste Wartungsversion des SANtricity-Betriebssystems aktualisieren, das für Ihre StorageGRID Appliance geeignet ist. Ermitteln Sie mit dem NetApp Interoperabilitäts-Matrix-Tool \ (IMT\) die zu verwenden ist. Wenden Sie sich an den technischen Support, wenn Sie Hilfe benötigen.' 
---
= Aktualisieren des SANtricity OS auf dem Storage Controller
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die optimale Funktion des Storage Controllers sicherzustellen, müssen Sie auf die neueste Wartungsversion des SANtricity-Betriebssystems aktualisieren, das für Ihre StorageGRID Appliance geeignet ist. Ermitteln Sie mithilfe des NetApp Interoperabilitäts-Matrix-Tools (IMT), welche Version Sie verwenden sollten. Wenden Sie sich an den technischen Support, wenn Sie Hilfe benötigen.

* Wenn der Storage-Controller SANtricity OS 08.42.20.00 (11.42) oder eine neuere Version verwendet, führen Sie das Upgrade mit dem Grid Manager durch.
+
link:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.html["Aktualisieren von SANtricity OS auf den Storage Controllern mit Grid Manager"]

* Wenn der Storage-Controller eine SANtricity OS-Version verwendet, die älter als 08.42.20.00 ist (11.42), führen Sie das Upgrade im Wartungsmodus durch.
+
link:upgrading-santricity-os-on-e2800-controller-using-maintenance-mode.html["Aktualisieren von SANtricity OS auf dem E2800 Controller mithilfe des Wartungsmodus"]



.Verwandte Informationen
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^]

https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab["NetApp Downloads mit SANtricity OS"^]

link:../monitor/index.html["Monitor  Fehlerbehebung"]
