---
permalink: troubleshoot/troubleshooting-delivery-platform-services-messages.html 
sidebar: sidebar 
keywords:  
summary: 'Der SMTT-Alarm (Total Events) wird im Grid Manager ausgelöst, wenn eine Plattformdienstnachricht an ein Ziel gesendet wird, das die Daten nicht annehmen kann.' 
---
= Fehlerbehebung bei der Bereitstellung von Plattform-Services-Meldungen (SMTT-Alarm)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der SMTT-Alarm (Total Events) wird im Grid Manager ausgelöst, wenn eine Plattformdienstnachricht an ein Ziel gesendet wird, das die Daten nicht annehmen kann.

.Über diese Aufgabe
So kann beispielsweise ein S3-Multipart-Upload erfolgreich sein, auch wenn die zugehörige Replizierungs- oder Benachrichtigungsmeldung nicht an den konfigurierten Endpunkt gesendet werden kann. Alternativ kann eine Nachricht für die CloudMirror Replizierung nicht bereitgestellt werden, wenn die Metadaten zu lang sind.

Der SMTT-Alarm enthält eine Meldung „Letztes Ereignis“, die lautet: `Failed to publish notifications for _bucket-name object key_` Für das letzte Objekt, dessen Benachrichtigung fehlgeschlagen ist.

Weitere Informationen zur Fehlerbehebung bei Plattform-Services finden Sie in den Anweisungen für die Administration von StorageGRID. Möglicherweise müssen Sie über den Tenant Manager auf den Mandanten zugreifen, um einen Plattformdienstfehler zu beheben.

.Schritte
. Um den Alarm anzuzeigen, wählen Sie *Nodes* *_site_* *_Grid Node_* *Events* aus.
. Letztes Ereignis oben in der Tabelle anzeigen.
+
Ereignismeldungen sind auch in aufgeführt `/var/local/log/bycast-err.log`.

. Befolgen Sie die Anweisungen im SMTT-Alarminhalt, um das Problem zu beheben.
. Klicken Sie auf *Ereignisanzahl zurücksetzen*.
. Benachrichtigen Sie den Mieter über die Objekte, deren Plattform-Services-Nachrichten nicht geliefert wurden.
. Weisen Sie den Mandanten an, die fehlgeschlagene Replikation oder Benachrichtigung durch Aktualisieren der Metadaten oder Tags des Objekts auszulösen.


.Verwandte Informationen
link:../admin/index.html["StorageGRID verwalten"]

link:../tenant/index.html["Verwenden Sie ein Mandantenkonto"]

link:../monitor/logs-files-reference.html["Referenz für Protokolldateien"]

link:../monitor/resetting-event-counts.html["Ereignisanzahl wird zurückgesetzt"]
