---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: Sie können einen Speicherpool bearbeiten, um seinen Namen zu ändern oder Standorte und Speicherklassen zu aktualisieren. 
---
= Bearbeiten eines Speicherpools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Speicherpool bearbeiten, um seinen Namen zu ändern oder Standorte und Speicherklassen zu aktualisieren.

.Was Sie benötigen
* Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.
* Sie müssen über spezifische Zugriffsberechtigungen verfügen.
* Sie müssen die Richtlinien zum Erstellen von Speicherpools überprüft haben.
* Wenn Sie einen Speicherpool bearbeiten möchten, der von einer Regel in der aktiven ILM-Richtlinie verwendet wird, müssen Sie prüfen, wie sich Ihre Änderungen auf die Platzierung der Objektdaten auswirken.


.Über diese Aufgabe
Wenn Sie einem Speicherpool, der in der aktiven ILM-Richtlinie verwendet wird, eine neue Speicherklasse hinzufügen, beachten Sie, dass die Speicherknoten in der neuen Speicherklasse nicht automatisch verwendet werden. Damit StorageGRID die Verwendung einer neuen Storage-Klasse erzwingen kann, müssen Sie eine neue ILM-Richtlinie aktivieren, nachdem Sie den bearbeiteten Speicherpool gespeichert haben.

.Schritte
. Wählen Sie *ILM* > *Storage Pools* aus.
+
Die Seite Speicherpools wird angezeigt.

. Wählen Sie das Optionsfeld für den Speicherpool aus, den Sie bearbeiten möchten.
+
Der Speicherpool Alle Speicherknoten kann nicht bearbeitet werden.

. Wählen Sie *Bearbeiten*.
. Ändern Sie bei Bedarf den Namen des Speicherpools.
. Wählen Sie bei Bedarf andere Standorte und Lagersorten aus.
+

NOTE: Sie können die Standort- oder Speicherklasse nicht ändern, wenn der Speicherpool in einem Erasure-Coding-Profil verwendet wird und die Änderung das Erasure-Coding-Schema ungültig machen würde. Wenn beispielsweise ein Speicherpool, der in einem Erasure-Coding-Profil verwendet wird, derzeit eine Speicherklasse mit nur einem Standort enthält, können Sie eine Speicherklasse mit zwei Standorten nicht verwenden, da die Änderung das Erasure-Coding-Schema ungültig machen würde.

. Wählen Sie *Speichern*.


.Nachdem Sie fertig sind
Wenn Sie einem Storage-Pool, der in der aktiven ILM-Richtlinie verwendet wird, eine neue Storage-Klasse hinzugefügt haben, aktivieren Sie eine neue ILM-Richtlinie, um die Verwendung der neuen Storage-Klasse durch StorageGRID zu erzwingen. Klonen Sie beispielsweise Ihre vorhandene ILM-Richtlinie und aktivieren Sie dann den Klon.
