---
permalink: ilm/removing-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: Sie können einen Speicherpool entfernen, der nicht verwendet wird. 
---
= Entfernen eines Speicherpools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Speicherpool entfernen, der nicht verwendet wird.

.Was Sie benötigen
* Sie müssen über einen unterstützten Browser beim Grid Manager angemeldet sein.
* Sie müssen über spezifische Zugriffsberechtigungen verfügen.


.Schritte
. Wählen Sie *ILM* > *Storage Pools* aus.
+
Die Seite Speicherpools wird angezeigt.

. Sehen Sie sich die Spalte ILM-Nutzung in der Tabelle an, um zu bestimmen, ob Sie den Speicherpool entfernen können.
+
Ein Speicherpool kann nicht entfernt werden, wenn er in einer ILM-Regel oder in einem Erasure Coding-Profil verwendet wird. Wählen Sie nach Bedarf *Details anzeigen* > *ILM-Nutzung* aus, um festzustellen, wo ein Speicherpool verwendet wird.

. Wenn der Speicherpool, den Sie entfernen möchten, nicht verwendet wird, aktivieren Sie das Optionsfeld.
. Wählen Sie *Entfernen*.
. Wählen Sie *OK*.

