---
permalink: fabricpool/example-ilm-policy-for-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example 
summary: Nutzen Sie diese einfache Beispielrichtlinie als Ausgangspunkt für Ihre eigenen ILM-Regeln und -Richtlinien. 
---
= Beispiel für eine ILM-Richtlinie für FabricPool-Daten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nutzen Sie diese einfache Beispielrichtlinie als Ausgangspunkt für Ihre eigenen ILM-Regeln und -Richtlinien.

Das Beispiel geht davon aus, dass Sie die ILM-Regeln und eine ILM-Richtlinie für ein StorageGRID System mit vier Storage-Nodes in einem einzelnen Datacenter in Denver, Colorado, entwerfen. Die FabricPool-Daten in diesem Beispiel verwenden einen Bucket mit dem Namen `fabricpool-bucket`.

[CAUTION]
====
Die folgenden ILM-Regeln und -Richtlinien sind nur Beispiele. Es gibt viele Möglichkeiten zur Konfiguration von ILM-Regeln. Vor der Aktivierung einer neuen Richtlinie sollte die vorgeschlagene Richtlinie simuliert werden, um zu bestätigen, dass sie wie vorgesehen funktioniert, um Inhalte vor Verlust zu schützen.

Weitere Informationen: link:../ilm/index.html["Objektmanagement mit ILM"]

====
.Schritte
. Erstellen Sie einen Speicherpool mit dem Namen *DEN*. Wählen Sie den Standort Denver aus.
. Erstellen Sie ein Erasure-Coding-Profil mit dem Namen *2 plus 1*. Wählen Sie die 2+1-Löschcodierung und den *DEN*-Speicherpool aus.
. Erstellen einer ILM-Regel, die sich nur auf die Daten in bezieht `fabricpool-bucket`. In dieser Beispielregel werden Kopien mit Verfahren zur Fehlerkorrektur erstellt.
+
[cols="1a,1a"]
|===
| Regeldefinition | Beispielwert 


 a| 
Regelname
 a| 
2 plus 1 Erasure Coding für FabricPool-Daten



 a| 
Bucket-Name
 a| 
`fabricpool-bucket`

Sie könnten auch nach dem FabricPool-Mandantenkonto filtern.



 a| 
Erweiterte Filterung
 a| 
Objektgröße (MB) größer als 0.2 MB.

*Hinweis:* FabricPool schreibt nur 4 MB Objekte, aber Sie müssen einen Filter für Objektgröße hinzufügen, da diese Regel das Erasure Coding verwendet.



 a| 
Referenzzeit
 a| 
Aufnahmezeit



 a| 
Platzierung
 a| 
Ab Tag 0 dauerhaft speichern



 a| 
Typ
 a| 
Erasure Coding



 a| 
Standort
 a| 
DEN (2 plus 1)



 a| 
Aufnahmeverhalten
 a| 
Ausgeglichen

|===
. Erstellen einer ILM-Regel, die zwei replizierte Kopien von Objekten erstellt, die nicht mit der ersten Regel übereinstimmt. Wählen Sie keinen grundlegenden Filter (Mandantenkonto oder Bucket-Name) oder erweiterte Filter aus.
+
[cols="1a,1a"]
|===
| Regeldefinition | Beispielwert 


 a| 
Regelname
 a| 
Zwei replizierte Kopien



 a| 
Bucket-Name
 a| 
_None_



 a| 
Erweiterte Filterung
 a| 
_None_



 a| 
Referenzzeit
 a| 
Aufnahmezeit



 a| 
Platzierung
 a| 
Ab Tag 0 dauerhaft speichern



 a| 
Typ
 a| 
Datenreplizierung



 a| 
Standort
 a| 
DEN



 a| 
Kopien
 a| 
2



 a| 
Aufnahmeverhalten
 a| 
Ausgeglichen

|===
. Erstellen Sie eine vorgeschlagene ILM-Richtlinie und wählen Sie beide Regeln aus. Da die Replikationsregel keine Filter verwendet, kann es sich um die Standardregel (letzte) für die Richtlinie handelt.
. Aufnahme von Testobjekten in das Raster
. Simulieren Sie die Richtlinie mit den Testobjekten, um das Verhalten zu überprüfen.
. Aktivieren Sie die Richtlinie.


Wenn diese Richtlinie aktiviert ist, speichert StorageGRID Objektdaten wie folgt:

* Die Daten-Tiering von FabricPool in `fabricpool-bucket` Wird mithilfe des 2+1-Schemas zur Einhaltung von Datenkonsistenz (Erasure Coding) codiert. Zwei Datenfragmente und ein Paritätsfragment werden auf drei verschiedenen Storage Nodes platziert.
* Alle Objekte in allen anderen Buckets werden repliziert. Es werden zwei Kopien erstellt und auf zwei verschiedenen Speicherknoten platziert.
* Die von Erasure Coding und replizierten Kopien werden in StorageGRID aufbewahrt, bis sie vom S3 Client gelöscht werden. StorageGRID ILM löscht diese Elemente nie.

